<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicole Lee">
<meta name="dcterms.date" content="2025-03-07">
<meta name="description" content="Leveraged machine learning algorithms like ordinal logistic regression and decision trees to achieving 92% prediction accuracy. Visualized key trends to support strategic recommendations for early policy intervention.">

<title>Assessing Fiscal Risk and Financial Stability – Nicole Lee</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nicole Lee</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Landing Page</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link active" data-scroll-target="#exploratory-data-analysis">1. Exploratory Data Analysis:</a>
  <ul class="collapse">
  <li><a href="#correlation-analysis" id="toc-correlation-analysis" class="nav-link" data-scroll-target="#correlation-analysis">Correlation Analysis:</a>
  <ul class="collapse">
  <li><a href="#correlation-analysis-using-ratios" id="toc-correlation-analysis-using-ratios" class="nav-link" data-scroll-target="#correlation-analysis-using-ratios">Correlation Analysis Using Ratios:</a></li>
  <li><a href="#correlation-analysis-using-other-numeric-variables" id="toc-correlation-analysis-using-other-numeric-variables" class="nav-link" data-scroll-target="#correlation-analysis-using-other-numeric-variables">Correlation Analysis Using Other Numeric Variables:</a></li>
  <li><a href="#summary-statistics-for-other-numeric-variables" id="toc-summary-statistics-for-other-numeric-variables" class="nav-link" data-scroll-target="#summary-statistics-for-other-numeric-variables">Summary Statistics for Other Numeric Variables:</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">Missing Values</a></li>
  <li><a href="#boxplots-points-and-risks" id="toc-boxplots-points-and-risks" class="nav-link" data-scroll-target="#boxplots-points-and-risks">Boxplots: Points and Risks</a></li>
  <li><a href="#boxplots-ratio-and-risks" id="toc-boxplots-ratio-and-risks" class="nav-link" data-scroll-target="#boxplots-ratio-and-risks">Boxplots: Ratio and Risks</a></li>
  <li><a href="#mean-and-mode-imputation" id="toc-mean-and-mode-imputation" class="nav-link" data-scroll-target="#mean-and-mode-imputation">Mean and mode imputation</a></li>
  <li><a href="#histogram-of-risk-levels" id="toc-histogram-of-risk-levels" class="nav-link" data-scroll-target="#histogram-of-risk-levels">Histogram of Risk Levels</a></li>
  </ul></li>
  <li><a href="#statistic-modeling" id="toc-statistic-modeling" class="nav-link" data-scroll-target="#statistic-modeling">2. Statistic Modeling:</a>
  <ul class="collapse">
  <li><a href="#ordinal-logistic-regression" id="toc-ordinal-logistic-regression" class="nav-link" data-scroll-target="#ordinal-logistic-regression">Ordinal logistic regression:</a></li>
  </ul></li>
  <li><a href="#predictive-modeling" id="toc-predictive-modeling" class="nav-link" data-scroll-target="#predictive-modeling">3. Predictive Modeling:</a>
  <ul class="collapse">
  <li><a href="#random-forests" id="toc-random-forests" class="nav-link" data-scroll-target="#random-forests">Random Forests:</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assessing Fiscal Risk and Financial Stability</h1>
</div>

<div>
  <div class="description">
    Leveraged machine learning algorithms like ordinal logistic regression and decision trees to achieving 92% prediction accuracy. Visualized key trends to support strategic recommendations for early policy intervention.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nicole Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 7, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Download the <a href="..\stats_140xp_paper.pdf">Report</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/nicol/Downloads/fy2019-20 (1).csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert risk columns (columns 13:23) into factors</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize levels: ALL CAPS</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>data[,<span class="dv">13</span>] <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data[,<span class="dv">13</span>])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(data[,<span class="dv">13</span>])<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"LOW"</span>, <span class="st">"MODERATE"</span>, <span class="st">"HIGH"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>){</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  data[,<span class="dv">13</span><span class="sc">+</span>i] <span class="ot">&lt;-</span> <span class="fu">factor</span>(data[,<span class="dv">13</span><span class="sc">+</span>i], <span class="at">order=</span><span class="cn">TRUE</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"LOW"</span>, <span class="st">"MODERATE"</span>, <span class="st">"HIGH"</span>))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Column num, Items 1: City Names 2-12: Rank 13-23: Risk 24-34: Points 35-44: Ratio 45-66: Other Numeric Data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Numeric Items</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>points <span class="ot">&lt;-</span> data[, <span class="dv">24</span><span class="sc">:</span><span class="dv">34</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>ratio <span class="ot">&lt;-</span> data[, <span class="dv">35</span><span class="sc">:</span><span class="dv">44</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>numeric <span class="ot">&lt;-</span> data[, <span class="dv">45</span><span class="sc">:</span><span class="dv">66</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exploratory-data-analysis" class="level1">
<h1>1. Exploratory Data Analysis:</h1>
<section id="correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis">Correlation Analysis:</h2>
<p>Consider take out some of the highly correlated variables when modeling</p>
<section id="correlation-analysis-using-ratios" class="level3">
<h3 class="anchored" data-anchor-id="correlation-analysis-using-ratios">Correlation Analysis Using Ratios:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ratio_corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(ratio, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>ratio_corr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            General_Fund_Reserves_Ratio Debt_Burden_Ratio
General_Fund_Reserves_Ratio                  1.00000000       0.005155050
Debt_Burden_Ratio                            0.00515505       1.000000000
Liquidity_Ratio                              0.33811237      -0.017499614
Revenue_Trends_Ratio                         0.04393613       0.046310907
Pension_Obligations_Ratio                   -0.15747725       0.045011789
Pension_Funding_Ratio                        0.13377685      -0.101198033
Pension_Costs_Ratio                         -0.20640017       0.018499816
Future_Pension_Costs_Ratio                  -0.18872225       0.009290444
OPEB_Obligations_Ratio                      -0.06737789       0.068615098
OPEB_Funding_Ratio                           0.19531425      -0.093349356
                            Liquidity_Ratio Revenue_Trends_Ratio
General_Fund_Reserves_Ratio     0.338112370          0.043936126
Debt_Burden_Ratio              -0.017499614          0.046310907
Liquidity_Ratio                 1.000000000         -0.001968421
Revenue_Trends_Ratio           -0.001968421          1.000000000
Pension_Obligations_Ratio      -0.220281682         -0.039903799
Pension_Funding_Ratio           0.157083948         -0.077086569
Pension_Costs_Ratio            -0.214179610         -0.019395935
Future_Pension_Costs_Ratio     -0.209027927         -0.049089502
OPEB_Obligations_Ratio         -0.084776650         -0.046797256
OPEB_Funding_Ratio              0.255285406         -0.107584591
                            Pension_Obligations_Ratio Pension_Funding_Ratio
General_Fund_Reserves_Ratio               -0.15747725            0.13377685
Debt_Burden_Ratio                          0.04501179           -0.10119803
Liquidity_Ratio                           -0.22028168            0.15708395
Revenue_Trends_Ratio                      -0.03990380           -0.07708657
Pension_Obligations_Ratio                  1.00000000           -0.28673182
Pension_Funding_Ratio                     -0.28673182            1.00000000
Pension_Costs_Ratio                        0.81012988           -0.42052344
Future_Pension_Costs_Ratio                 0.79928352           -0.57846759
OPEB_Obligations_Ratio                     0.38775799           -0.06788278
OPEB_Funding_Ratio                        -0.25837661            0.15871182
                            Pension_Costs_Ratio Future_Pension_Costs_Ratio
General_Fund_Reserves_Ratio         -0.20640017               -0.188722254
Debt_Burden_Ratio                    0.01849982                0.009290444
Liquidity_Ratio                     -0.21417961               -0.209027927
Revenue_Trends_Ratio                -0.01939593               -0.049089502
Pension_Obligations_Ratio            0.81012988                0.799283517
Pension_Funding_Ratio               -0.42052344               -0.578467593
Pension_Costs_Ratio                  1.00000000                0.851604010
Future_Pension_Costs_Ratio           0.85160401                1.000000000
OPEB_Obligations_Ratio               0.27051688                0.278913672
OPEB_Funding_Ratio                  -0.20429957               -0.209207470
                            OPEB_Obligations_Ratio OPEB_Funding_Ratio
General_Fund_Reserves_Ratio            -0.06737789         0.19531425
Debt_Burden_Ratio                       0.06861510        -0.09334936
Liquidity_Ratio                        -0.08477665         0.25528541
Revenue_Trends_Ratio                   -0.04679726        -0.10758459
Pension_Obligations_Ratio               0.38775799        -0.25837661
Pension_Funding_Ratio                  -0.06788278         0.15871182
Pension_Costs_Ratio                     0.27051688        -0.20429957
Future_Pension_Costs_Ratio              0.27891367        -0.20920747
OPEB_Obligations_Ratio                  1.00000000        -0.38722256
OPEB_Funding_Ratio                     -0.38722256         1.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">heatmap</span>(ratio_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="correlation-analysis-using-other-numeric-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlation-analysis-using-other-numeric-variables">Correlation Analysis Using Other Numeric Variables:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>numeric_corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>numeric_corr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                           Population
Population                                                                 1.00000000
Unemployment_rate                                                          0.10458595
General_Fund_Cash_and_Investments                                          0.57453187
General_Fund_Liabilities                                                   0.60112910
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.67300823
Government_Wide_Revenue                                                    0.83252773
Change_GF_Unrestricted_Fund_Balances                                      -0.05122791
GF_Unrestricted_Fund_Balances                                              0.59262806
GF_Expenditures_Transfers_Out                                              0.83192423
GF_Unrestricted_FB_PY_PY                                                   0.53903592
GF_Unrestricted_FB_PY                                                      0.60847563
GF_Unrestricted_FB_CY                                                      0.59262806
GF_Rev_PY_PY                                                               0.82733012
GF_Rev_PY                                                                  0.82976920
GF_Rev_CY                                                                  0.84695900
Net_Pension_Liability_or_Asset                                             0.81784437
Pension_Related_Debt                                                       0.32108175
Pension_Assets                                                             0.82653615
Accrued_Pension_Liabilities                                                0.82658650
Actuarially_Determined_Pension_Contributions                               0.81326159
Projected_Pension_Contribution                                             0.81969997
Net_OPEB_Liability_or_Asset                                                0.54888106
                                                                          Unemployment_rate
Population                                                                     0.1045859539
Unemployment_rate                                                              1.0000000000
General_Fund_Cash_and_Investments                                             -0.0542933134
General_Fund_Liabilities                                                       0.0212190349
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations      0.0386830382
Government_Wide_Revenue                                                        0.0039532113
Change_GF_Unrestricted_Fund_Balances                                          -0.0562638842
GF_Unrestricted_Fund_Balances                                                 -0.0648134571
GF_Expenditures_Transfers_Out                                                  0.0098504456
GF_Unrestricted_FB_PY_PY                                                      -0.0586534938
GF_Unrestricted_FB_PY                                                         -0.0600948138
GF_Unrestricted_FB_CY                                                         -0.0648134571
GF_Rev_PY_PY                                                                   0.0044085224
GF_Rev_PY                                                                      0.0004024498
GF_Rev_CY                                                                      0.0031155336
Net_Pension_Liability_or_Asset                                                 0.0220704718
Pension_Related_Debt                                                           0.0969817437
Pension_Assets                                                                 0.0436271464
Accrued_Pension_Liabilities                                                    0.0345197300
Actuarially_Determined_Pension_Contributions                                   0.0183949195
Projected_Pension_Contribution                                                 0.0153072919
Net_OPEB_Liability_or_Asset                                                    0.0708310557
                                                                          General_Fund_Cash_and_Investments
Population                                                                                       0.57453187
Unemployment_rate                                                                               -0.05429331
General_Fund_Cash_and_Investments                                                                1.00000000
General_Fund_Liabilities                                                                         0.82028822
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                        0.40020185
Government_Wide_Revenue                                                                          0.66020381
Change_GF_Unrestricted_Fund_Balances                                                            -0.04356678
GF_Unrestricted_Fund_Balances                                                                    0.81081400
GF_Expenditures_Transfers_Out                                                                    0.79730538
GF_Unrestricted_FB_PY_PY                                                                         0.84175499
GF_Unrestricted_FB_PY                                                                            0.88359469
GF_Unrestricted_FB_CY                                                                            0.81081400
GF_Rev_PY_PY                                                                                     0.81259230
GF_Rev_PY                                                                                        0.81246633
GF_Rev_CY                                                                                        0.80984833
Net_Pension_Liability_or_Asset                                                                   0.70085542
Pension_Related_Debt                                                                             0.34136911
Pension_Assets                                                                                   0.67024018
Accrued_Pension_Liabilities                                                                      0.69290692
Actuarially_Determined_Pension_Contributions                                                     0.74376035
Projected_Pension_Contribution                                                                   0.69843112
Net_OPEB_Liability_or_Asset                                                                      0.62947284
                                                                          General_Fund_Liabilities
Population                                                                              0.60112910
Unemployment_rate                                                                       0.02121903
General_Fund_Cash_and_Investments                                                       0.82028822
General_Fund_Liabilities                                                                1.00000000
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations               0.51213626
Government_Wide_Revenue                                                                 0.68284422
Change_GF_Unrestricted_Fund_Balances                                                   -0.02621429
GF_Unrestricted_Fund_Balances                                                           0.49972955
GF_Expenditures_Transfers_Out                                                           0.82519244
GF_Unrestricted_FB_PY_PY                                                                0.54698719
GF_Unrestricted_FB_PY                                                                   0.58521821
GF_Unrestricted_FB_CY                                                                   0.49972955
GF_Rev_PY_PY                                                                            0.83150876
GF_Rev_PY                                                                               0.82761768
GF_Rev_CY                                                                               0.82464213
Net_Pension_Liability_or_Asset                                                          0.78867980
Pension_Related_Debt                                                                    0.44621468
Pension_Assets                                                                          0.75632879
Accrued_Pension_Liabilities                                                             0.78147285
Actuarially_Determined_Pension_Contributions                                            0.83237643
Projected_Pension_Contribution                                                          0.77097538
Net_OPEB_Liability_or_Asset                                                             0.76640255
                                                                          Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations
Population                                                                                                                               0.67300823
Unemployment_rate                                                                                                                        0.03868304
General_Fund_Cash_and_Investments                                                                                                        0.40020185
General_Fund_Liabilities                                                                                                                 0.51213626
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                                                                1.00000000
Government_Wide_Revenue                                                                                                                  0.86977191
Change_GF_Unrestricted_Fund_Balances                                                                                                    -0.02268537
GF_Unrestricted_Fund_Balances                                                                                                            0.41945346
GF_Expenditures_Transfers_Out                                                                                                            0.70755784
GF_Unrestricted_FB_PY_PY                                                                                                                 0.42409677
GF_Unrestricted_FB_PY                                                                                                                    0.45766423
GF_Unrestricted_FB_CY                                                                                                                    0.41945346
GF_Rev_PY_PY                                                                                                                             0.70618594
GF_Rev_PY                                                                                                                                0.70353951
GF_Rev_CY                                                                                                                                0.68849011
Net_Pension_Liability_or_Asset                                                                                                           0.72984540
Pension_Related_Debt                                                                                                                     0.31398876
Pension_Assets                                                                                                                           0.82293903
Accrued_Pension_Liabilities                                                                                                              0.79242509
Actuarially_Determined_Pension_Contributions                                                                                             0.74042984
Projected_Pension_Contribution                                                                                                           0.75281756
Net_OPEB_Liability_or_Asset                                                                                                              0.37126679
                                                                          Government_Wide_Revenue
Population                                                                            0.832527732
Unemployment_rate                                                                     0.003953211
General_Fund_Cash_and_Investments                                                     0.660203806
General_Fund_Liabilities                                                              0.682844220
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations             0.869771907
Government_Wide_Revenue                                                               1.000000000
Change_GF_Unrestricted_Fund_Balances                                                 -0.039044249
GF_Unrestricted_Fund_Balances                                                         0.645404929
GF_Expenditures_Transfers_Out                                                         0.920877340
GF_Unrestricted_FB_PY_PY                                                              0.645988710
GF_Unrestricted_FB_PY                                                                 0.696345139
GF_Unrestricted_FB_CY                                                                 0.645404929
GF_Rev_PY_PY                                                                          0.917778297
GF_Rev_PY                                                                             0.920687066
GF_Rev_CY                                                                             0.916714320
Net_Pension_Liability_or_Asset                                                        0.919065377
Pension_Related_Debt                                                                  0.340129269
Pension_Assets                                                                        0.947113085
Accrued_Pension_Liabilities                                                           0.943154540
Actuarially_Determined_Pension_Contributions                                          0.925837620
Projected_Pension_Contribution                                                        0.934939413
Net_OPEB_Liability_or_Asset                                                           0.592023702
                                                                          Change_GF_Unrestricted_Fund_Balances
Population                                                                                         -0.05122791
Unemployment_rate                                                                                  -0.05626388
General_Fund_Cash_and_Investments                                                                  -0.04356678
General_Fund_Liabilities                                                                           -0.02621429
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                          -0.02268537
Government_Wide_Revenue                                                                            -0.03904425
Change_GF_Unrestricted_Fund_Balances                                                                1.00000000
GF_Unrestricted_Fund_Balances                                                                      -0.01499481
GF_Expenditures_Transfers_Out                                                                      -0.04651847
GF_Unrestricted_FB_PY_PY                                                                           -0.05422690
GF_Unrestricted_FB_PY                                                                              -0.05574819
GF_Unrestricted_FB_CY                                                                              -0.01499481
GF_Rev_PY_PY                                                                                       -0.04722298
GF_Rev_PY                                                                                          -0.04739149
GF_Rev_CY                                                                                          -0.04687453
Net_Pension_Liability_or_Asset                                                                     -0.03771912
Pension_Related_Debt                                                                               -0.01242512
Pension_Assets                                                                                     -0.03674397
Accrued_Pension_Liabilities                                                                        -0.03705983
Actuarially_Determined_Pension_Contributions                                                       -0.03689249
Projected_Pension_Contribution                                                                     -0.03781699
Net_OPEB_Liability_or_Asset                                                                        -0.03009563
                                                                          GF_Unrestricted_Fund_Balances
Population                                                                                   0.59262806
Unemployment_rate                                                                           -0.06481346
General_Fund_Cash_and_Investments                                                            0.81081400
General_Fund_Liabilities                                                                     0.49972955
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                    0.41945346
Government_Wide_Revenue                                                                      0.64540493
Change_GF_Unrestricted_Fund_Balances                                                        -0.01499481
GF_Unrestricted_Fund_Balances                                                                1.00000000
GF_Expenditures_Transfers_Out                                                                0.70002638
GF_Unrestricted_FB_PY_PY                                                                     0.88375324
GF_Unrestricted_FB_PY                                                                        0.91987988
GF_Unrestricted_FB_CY                                                                        1.00000000
GF_Rev_PY_PY                                                                                 0.70933864
GF_Rev_PY                                                                                    0.71031419
GF_Rev_CY                                                                                    0.71160927
Net_Pension_Liability_or_Asset                                                               0.58238500
Pension_Related_Debt                                                                         0.21226839
Pension_Assets                                                                               0.59335052
Accrued_Pension_Liabilities                                                                  0.59117154
Actuarially_Determined_Pension_Contributions                                                 0.60444510
Projected_Pension_Contribution                                                               0.59581107
Net_OPEB_Liability_or_Asset                                                                  0.39824983
                                                                          GF_Expenditures_Transfers_Out
Population                                                                                  0.831924234
Unemployment_rate                                                                           0.009850446
General_Fund_Cash_and_Investments                                                           0.797305376
General_Fund_Liabilities                                                                    0.825192441
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                   0.707557837
Government_Wide_Revenue                                                                     0.920877340
Change_GF_Unrestricted_Fund_Balances                                                       -0.046518470
GF_Unrestricted_Fund_Balances                                                               0.700026383
GF_Expenditures_Transfers_Out                                                               1.000000000
GF_Unrestricted_FB_PY_PY                                                                    0.739954850
GF_Unrestricted_FB_PY                                                                       0.776593988
GF_Unrestricted_FB_CY                                                                       0.700026383
GF_Rev_PY_PY                                                                                0.993869518
GF_Rev_PY                                                                                   0.993394697
GF_Rev_CY                                                                                   0.992036052
Net_Pension_Liability_or_Asset                                                              0.943431022
Pension_Related_Debt                                                                        0.408407662
Pension_Assets                                                                              0.941921177
Accrued_Pension_Liabilities                                                                 0.950516198
Actuarially_Determined_Pension_Contributions                                                0.962830312
Projected_Pension_Contribution                                                              0.948492219
Net_OPEB_Liability_or_Asset                                                                 0.709776285
                                                                          GF_Unrestricted_FB_PY_PY
Population                                                                              0.53903592
Unemployment_rate                                                                      -0.05865349
General_Fund_Cash_and_Investments                                                       0.84175499
General_Fund_Liabilities                                                                0.54698719
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations               0.42409677
Government_Wide_Revenue                                                                 0.64598871
Change_GF_Unrestricted_Fund_Balances                                                   -0.05422690
GF_Unrestricted_Fund_Balances                                                           0.88375324
GF_Expenditures_Transfers_Out                                                           0.73995485
GF_Unrestricted_FB_PY_PY                                                                1.00000000
GF_Unrestricted_FB_PY                                                                   0.97575550
GF_Unrestricted_FB_CY                                                                   0.88375324
GF_Rev_PY_PY                                                                            0.74687428
GF_Rev_PY                                                                               0.74036509
GF_Rev_CY                                                                               0.72794307
Net_Pension_Liability_or_Asset                                                          0.58621253
Pension_Related_Debt                                                                    0.16759023
Pension_Assets                                                                          0.60243181
Accrued_Pension_Liabilities                                                             0.60181214
Actuarially_Determined_Pension_Contributions                                            0.61746451
Projected_Pension_Contribution                                                          0.61646760
Net_OPEB_Liability_or_Asset                                                             0.38179034
                                                                          GF_Unrestricted_FB_PY
Population                                                                           0.60847563
Unemployment_rate                                                                   -0.06009481
General_Fund_Cash_and_Investments                                                    0.88359469
General_Fund_Liabilities                                                             0.58521821
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations            0.45766423
Government_Wide_Revenue                                                              0.69634514
Change_GF_Unrestricted_Fund_Balances                                                -0.05574819
GF_Unrestricted_Fund_Balances                                                        0.91987988
GF_Expenditures_Transfers_Out                                                        0.77659399
GF_Unrestricted_FB_PY_PY                                                             0.97575550
GF_Unrestricted_FB_PY                                                                1.00000000
GF_Unrestricted_FB_CY                                                                0.91987988
GF_Rev_PY_PY                                                                         0.78388183
GF_Rev_PY                                                                            0.78251955
GF_Rev_CY                                                                            0.77501546
Net_Pension_Liability_or_Asset                                                       0.63809415
Pension_Related_Debt                                                                 0.22281616
Pension_Assets                                                                       0.64363901
Accrued_Pension_Liabilities                                                          0.64556000
Actuarially_Determined_Pension_Contributions                                         0.66738140
Projected_Pension_Contribution                                                       0.65684089
Net_OPEB_Liability_or_Asset                                                          0.44651167
                                                                          GF_Unrestricted_FB_CY
Population                                                                           0.59262806
Unemployment_rate                                                                   -0.06481346
General_Fund_Cash_and_Investments                                                    0.81081400
General_Fund_Liabilities                                                             0.49972955
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations            0.41945346
Government_Wide_Revenue                                                              0.64540493
Change_GF_Unrestricted_Fund_Balances                                                -0.01499481
GF_Unrestricted_Fund_Balances                                                        1.00000000
GF_Expenditures_Transfers_Out                                                        0.70002638
GF_Unrestricted_FB_PY_PY                                                             0.88375324
GF_Unrestricted_FB_PY                                                                0.91987988
GF_Unrestricted_FB_CY                                                                1.00000000
GF_Rev_PY_PY                                                                         0.70933864
GF_Rev_PY                                                                            0.71031419
GF_Rev_CY                                                                            0.71160927
Net_Pension_Liability_or_Asset                                                       0.58238500
Pension_Related_Debt                                                                 0.21226839
Pension_Assets                                                                       0.59335052
Accrued_Pension_Liabilities                                                          0.59117154
Actuarially_Determined_Pension_Contributions                                         0.60444510
Projected_Pension_Contribution                                                       0.59581107
Net_OPEB_Liability_or_Asset                                                          0.39824983
                                                                          GF_Rev_PY_PY
Population                                                                 0.827330122
Unemployment_rate                                                          0.004408522
General_Fund_Cash_and_Investments                                          0.812592300
General_Fund_Liabilities                                                   0.831508760
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.706185937
Government_Wide_Revenue                                                    0.917778297
Change_GF_Unrestricted_Fund_Balances                                      -0.047222975
GF_Unrestricted_Fund_Balances                                              0.709338642
GF_Expenditures_Transfers_Out                                              0.993869518
GF_Unrestricted_FB_PY_PY                                                   0.746874284
GF_Unrestricted_FB_PY                                                      0.783881834
GF_Unrestricted_FB_CY                                                      0.709338642
GF_Rev_PY_PY                                                               1.000000000
GF_Rev_PY                                                                  0.998179565
GF_Rev_CY                                                                  0.994215761
Net_Pension_Liability_or_Asset                                             0.944384484
Pension_Related_Debt                                                       0.396606511
Pension_Assets                                                             0.939698514
Accrued_Pension_Liabilities                                                0.950509065
Actuarially_Determined_Pension_Contributions                               0.964981424
Projected_Pension_Contribution                                             0.951174292
Net_OPEB_Liability_or_Asset                                                0.719772928
                                                                              GF_Rev_PY
Population                                                                 0.8297692013
Unemployment_rate                                                          0.0004024498
General_Fund_Cash_and_Investments                                          0.8124663319
General_Fund_Liabilities                                                   0.8276176842
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.7035395130
Government_Wide_Revenue                                                    0.9206870656
Change_GF_Unrestricted_Fund_Balances                                      -0.0473914872
GF_Unrestricted_Fund_Balances                                              0.7103141940
GF_Expenditures_Transfers_Out                                              0.9933946966
GF_Unrestricted_FB_PY_PY                                                   0.7403650909
GF_Unrestricted_FB_PY                                                      0.7825195500
GF_Unrestricted_FB_CY                                                      0.7103141940
GF_Rev_PY_PY                                                               0.9981795653
GF_Rev_PY                                                                  1.0000000000
GF_Rev_CY                                                                  0.9966048535
Net_Pension_Liability_or_Asset                                             0.9482628313
Pension_Related_Debt                                                       0.3898758631
Pension_Assets                                                             0.9392259489
Accrued_Pension_Liabilities                                                0.9517409572
Actuarially_Determined_Pension_Contributions                               0.9674875286
Projected_Pension_Contribution                                             0.9540846675
Net_OPEB_Liability_or_Asset                                                0.7202161505
                                                                             GF_Rev_CY
Population                                                                 0.846959004
Unemployment_rate                                                          0.003115534
General_Fund_Cash_and_Investments                                          0.809848335
General_Fund_Liabilities                                                   0.824642127
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.688490112
Government_Wide_Revenue                                                    0.916714320
Change_GF_Unrestricted_Fund_Balances                                      -0.046874527
GF_Unrestricted_Fund_Balances                                              0.711609268
GF_Expenditures_Transfers_Out                                              0.992036052
GF_Unrestricted_FB_PY_PY                                                   0.727943067
GF_Unrestricted_FB_PY                                                      0.775015459
GF_Unrestricted_FB_CY                                                      0.711609268
GF_Rev_PY_PY                                                               0.994215761
GF_Rev_PY                                                                  0.996604853
GF_Rev_CY                                                                  1.000000000
Net_Pension_Liability_or_Asset                                             0.950682978
Pension_Related_Debt                                                       0.392488992
Pension_Assets                                                             0.937964723
Accrued_Pension_Liabilities                                                0.951628735
Actuarially_Determined_Pension_Contributions                               0.967147219
Projected_Pension_Contribution                                             0.954143576
Net_OPEB_Liability_or_Asset                                                0.723539196
                                                                          Net_Pension_Liability_or_Asset
Population                                                                                    0.81784437
Unemployment_rate                                                                             0.02207047
General_Fund_Cash_and_Investments                                                             0.70085542
General_Fund_Liabilities                                                                      0.78867980
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                     0.72984540
Government_Wide_Revenue                                                                       0.91906538
Change_GF_Unrestricted_Fund_Balances                                                         -0.03771912
GF_Unrestricted_Fund_Balances                                                                 0.58238500
GF_Expenditures_Transfers_Out                                                                 0.94343102
GF_Unrestricted_FB_PY_PY                                                                      0.58621253
GF_Unrestricted_FB_PY                                                                         0.63809415
GF_Unrestricted_FB_CY                                                                         0.58238500
GF_Rev_PY_PY                                                                                  0.94438448
GF_Rev_PY                                                                                     0.94826283
GF_Rev_CY                                                                                     0.95068298
Net_Pension_Liability_or_Asset                                                                1.00000000
Pension_Related_Debt                                                                          0.38653164
Pension_Assets                                                                                0.96516600
Accrued_Pension_Liabilities                                                                   0.98595204
Actuarially_Determined_Pension_Contributions                                                  0.98763331
Projected_Pension_Contribution                                                                0.98956209
Net_OPEB_Liability_or_Asset                                                                   0.72874228
                                                                          Pension_Related_Debt
Population                                                                          0.32108175
Unemployment_rate                                                                   0.09698174
General_Fund_Cash_and_Investments                                                   0.34136911
General_Fund_Liabilities                                                            0.44621468
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations           0.31398876
Government_Wide_Revenue                                                             0.34012927
Change_GF_Unrestricted_Fund_Balances                                               -0.01242512
GF_Unrestricted_Fund_Balances                                                       0.21226839
GF_Expenditures_Transfers_Out                                                       0.40840766
GF_Unrestricted_FB_PY_PY                                                            0.16759023
GF_Unrestricted_FB_PY                                                               0.22281616
GF_Unrestricted_FB_CY                                                               0.21226839
GF_Rev_PY_PY                                                                        0.39660651
GF_Rev_PY                                                                           0.38987586
GF_Rev_CY                                                                           0.39248899
Net_Pension_Liability_or_Asset                                                      0.38653164
Pension_Related_Debt                                                                1.00000000
Pension_Assets                                                                      0.46475622
Accrued_Pension_Liabilities                                                         0.41668538
Actuarially_Determined_Pension_Contributions                                        0.42434185
Projected_Pension_Contribution                                                      0.30616455
Net_OPEB_Liability_or_Asset                                                         0.50096801
                                                                          Pension_Assets
Population                                                                    0.82653615
Unemployment_rate                                                             0.04362715
General_Fund_Cash_and_Investments                                             0.67024018
General_Fund_Liabilities                                                      0.75632879
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations     0.82293903
Government_Wide_Revenue                                                       0.94711309
Change_GF_Unrestricted_Fund_Balances                                         -0.03674397
GF_Unrestricted_Fund_Balances                                                 0.59335052
GF_Expenditures_Transfers_Out                                                 0.94192118
GF_Unrestricted_FB_PY_PY                                                      0.60243181
GF_Unrestricted_FB_PY                                                         0.64363901
GF_Unrestricted_FB_CY                                                         0.59335052
GF_Rev_PY_PY                                                                  0.93969851
GF_Rev_PY                                                                     0.93922595
GF_Rev_CY                                                                     0.93796472
Net_Pension_Liability_or_Asset                                                0.96516600
Pension_Related_Debt                                                          0.46475622
Pension_Assets                                                                1.00000000
Accrued_Pension_Liabilities                                                   0.99362133
Actuarially_Determined_Pension_Contributions                                  0.97133418
Projected_Pension_Contribution                                                0.96610488
Net_OPEB_Liability_or_Asset                                                   0.65275687
                                                                          Accrued_Pension_Liabilities
Population                                                                                 0.82658650
Unemployment_rate                                                                          0.03451973
General_Fund_Cash_and_Investments                                                          0.69290692
General_Fund_Liabilities                                                                   0.78147285
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                  0.79242509
Government_Wide_Revenue                                                                    0.94315454
Change_GF_Unrestricted_Fund_Balances                                                      -0.03705983
GF_Unrestricted_Fund_Balances                                                              0.59117154
GF_Expenditures_Transfers_Out                                                              0.95051620
GF_Unrestricted_FB_PY_PY                                                                   0.60181214
GF_Unrestricted_FB_PY                                                                      0.64556000
GF_Unrestricted_FB_CY                                                                      0.59117154
GF_Rev_PY_PY                                                                               0.95050907
GF_Rev_PY                                                                                  0.95174096
GF_Rev_CY                                                                                  0.95162874
Net_Pension_Liability_or_Asset                                                             0.98595204
Pension_Related_Debt                                                                       0.41668538
Pension_Assets                                                                             0.99362133
Accrued_Pension_Liabilities                                                                1.00000000
Actuarially_Determined_Pension_Contributions                                               0.98629441
Projected_Pension_Contribution                                                             0.98727071
Net_OPEB_Liability_or_Asset                                                                0.68742391
                                                                          Actuarially_Determined_Pension_Contributions
Population                                                                                                  0.81326159
Unemployment_rate                                                                                           0.01839492
General_Fund_Cash_and_Investments                                                                           0.74376035
General_Fund_Liabilities                                                                                    0.83237643
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                                   0.74042984
Government_Wide_Revenue                                                                                     0.92583762
Change_GF_Unrestricted_Fund_Balances                                                                       -0.03689249
GF_Unrestricted_Fund_Balances                                                                               0.60444510
GF_Expenditures_Transfers_Out                                                                               0.96283031
GF_Unrestricted_FB_PY_PY                                                                                    0.61746451
GF_Unrestricted_FB_PY                                                                                       0.66738140
GF_Unrestricted_FB_CY                                                                                       0.60444510
GF_Rev_PY_PY                                                                                                0.96498142
GF_Rev_PY                                                                                                   0.96748753
GF_Rev_CY                                                                                                   0.96714722
Net_Pension_Liability_or_Asset                                                                              0.98763331
Pension_Related_Debt                                                                                        0.42434185
Pension_Assets                                                                                              0.97133418
Accrued_Pension_Liabilities                                                                                 0.98629441
Actuarially_Determined_Pension_Contributions                                                                1.00000000
Projected_Pension_Contribution                                                                              0.98154011
Net_OPEB_Liability_or_Asset                                                                                 0.74131614
                                                                          Projected_Pension_Contribution
Population                                                                                    0.81969997
Unemployment_rate                                                                             0.01530729
General_Fund_Cash_and_Investments                                                             0.69843112
General_Fund_Liabilities                                                                      0.77097538
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                     0.75281756
Government_Wide_Revenue                                                                       0.93493941
Change_GF_Unrestricted_Fund_Balances                                                         -0.03781699
GF_Unrestricted_Fund_Balances                                                                 0.59581107
GF_Expenditures_Transfers_Out                                                                 0.94849222
GF_Unrestricted_FB_PY_PY                                                                      0.61646760
GF_Unrestricted_FB_PY                                                                         0.65684089
GF_Unrestricted_FB_CY                                                                         0.59581107
GF_Rev_PY_PY                                                                                  0.95117429
GF_Rev_PY                                                                                     0.95408467
GF_Rev_CY                                                                                     0.95414358
Net_Pension_Liability_or_Asset                                                                0.98956209
Pension_Related_Debt                                                                          0.30616455
Pension_Assets                                                                                0.96610488
Accrued_Pension_Liabilities                                                                   0.98727071
Actuarially_Determined_Pension_Contributions                                                  0.98154011
Projected_Pension_Contribution                                                                1.00000000
Net_OPEB_Liability_or_Asset                                                                   0.68834578
                                                                          Net_OPEB_Liability_or_Asset
Population                                                                                 0.54888106
Unemployment_rate                                                                          0.07083106
General_Fund_Cash_and_Investments                                                          0.62947284
General_Fund_Liabilities                                                                   0.76640255
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                  0.37126679
Government_Wide_Revenue                                                                    0.59202370
Change_GF_Unrestricted_Fund_Balances                                                      -0.03009563
GF_Unrestricted_Fund_Balances                                                              0.39824983
GF_Expenditures_Transfers_Out                                                              0.70977629
GF_Unrestricted_FB_PY_PY                                                                   0.38179034
GF_Unrestricted_FB_PY                                                                      0.44651167
GF_Unrestricted_FB_CY                                                                      0.39824983
GF_Rev_PY_PY                                                                               0.71977293
GF_Rev_PY                                                                                  0.72021615
GF_Rev_CY                                                                                  0.72353920
Net_Pension_Liability_or_Asset                                                             0.72874228
Pension_Related_Debt                                                                       0.50096801
Pension_Assets                                                                             0.65275687
Accrued_Pension_Liabilities                                                                0.68742391
Actuarially_Determined_Pension_Contributions                                               0.74131614
Projected_Pension_Contribution                                                             0.68834578
Net_OPEB_Liability_or_Asset                                                                1.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">heatmap</span>(numeric_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary-statistics-for-other-numeric-variables" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics-for-other-numeric-variables">Summary Statistics for Other Numeric Variables:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data[<span class="dv">45</span><span class="sc">:</span><span class="dv">66</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Population      Unemployment_rate General_Fund_Cash_and_Investments
 Min.   :    285   Min.   :0.00000   Min.   :0.000e+00                
 1st Qu.:  12513   1st Qu.:0.07300   1st Qu.:5.903e+06                
 Median :  34934   Median :0.09100   Median :1.579e+07                
 Mean   :  74733   Mean   :0.09621   Mean   :4.528e+07                
 3rd Qu.:  78926   3rd Qu.:0.11500   3rd Qu.:3.674e+07                
 Max.   :3970219   Max.   :0.34100   Max.   :3.492e+09                
                   NA's   :9         NA's   :1                        
 General_Fund_Liabilities
 Min.   :1.696e+04       
 1st Qu.:1.287e+06       
 Median :3.063e+06       
 Mean   :1.269e+07       
 3rd Qu.:7.089e+06       
 Max.   :1.331e+09       
 NA's   :1               
 Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations
 Min.   :0.000e+00                                                        
 1st Qu.:6.536e+06                                                        
 Median :2.280e+07                                                        
 Mean   :2.352e+08                                                        
 3rd Qu.:7.297e+07                                                        
 Max.   :3.599e+10                                                        
 NA's   :1                                                                
 Government_Wide_Revenue Change_GF_Unrestricted_Fund_Balances
 Min.   :4.330e+05       Min.   : -0.770                     
 1st Qu.:2.232e+07       1st Qu.: -0.010                     
 Median :5.678e+07       Median :  0.070                     
 Mean   :2.048e+08       Mean   :  1.632                     
 3rd Qu.:1.300e+08       3rd Qu.:  0.190                     
 Max.   :1.746e+10       Max.   :312.630                     
 NA's   :1               NA's   :1                           
 GF_Unrestricted_Fund_Balances GF_Expenditures_Transfers_Out
 Min.   :  -8141906            Min.   :7.204e+04            
 1st Qu.:   6068089            1st Qu.:1.312e+07            
 Median :  15923906            Median :3.234e+07            
 Mean   :  39070057            Mean   :9.358e+07            
 3rd Qu.:  36140557            3rd Qu.:7.498e+07            
 Max.   :2455579000            Max.   :6.179e+09            
 NA's   :1                     NA's   :1                    
 GF_Unrestricted_FB_PY_PY GF_Unrestricted_FB_PY GF_Unrestricted_FB_CY
 Min.   : -17564262       Min.   :  -9959177    Min.   :  -8141906   
 1st Qu.:   5236011       1st Qu.:   5570489    1st Qu.:   6068089   
 Median :  14149500       Median :  16072906    Median :  15923906   
 Mean   :  34203098       Mean   :  38146357    Mean   :  39070057   
 3rd Qu.:  31310428       3rd Qu.:  35646382    3rd Qu.:  36140557   
 Max.   :2076452000       Max.   :2390787000    Max.   :2455579000   
 NA's   :2                NA's   :1             NA's   :1            
  GF_Rev_PY_PY         GF_Rev_PY           GF_Rev_CY        
 Min.   :1.530e+05   Min.   :1.972e+05   Min.   :1.799e+05  
 1st Qu.:1.205e+07   1st Qu.:1.284e+07   1st Qu.:1.292e+07  
 Median :2.907e+07   Median :3.113e+07   Median :3.046e+07  
 Mean   :8.223e+07   Mean   :9.008e+07   Mean   :8.942e+07  
 3rd Qu.:6.566e+07   3rd Qu.:7.114e+07   3rd Qu.:7.243e+07  
 Max.   :5.250e+09   Max.   :5.890e+09   Max.   :5.745e+09  
 NA's   :2           NA's   :1           NA's   :1          
 Net_Pension_Liability_or_Asset Pension_Related_Debt Pension_Assets     
 Min.   :-244990000             Min.   :        0    Min.   :5.984e+05  
 1st Qu.:   8067243             1st Qu.:        0    1st Qu.:2.902e+07  
 Median :  29415004             Median :        0    Median :9.008e+07  
 Mean   : 134881952             Mean   :  7336554    Mean   :4.559e+08  
 3rd Qu.: 102298823             3rd Qu.:        0    3rd Qu.:2.643e+08  
 Max.   :8541000000             Max.   :484258000    Max.   :4.906e+10  
 NA's   :14                     NA's   :14           NA's   :14         
 Accrued_Pension_Liabilities Actuarially_Determined_Pension_Contributions
 Min.   :6.333e+05           Min.   :3.087e+04                           
 1st Qu.:3.821e+07           1st Qu.:9.864e+05                           
 Median :1.262e+08           Median :3.367e+06                           
 Mean   :5.930e+08           Mean   :1.679e+07                           
 3rd Qu.:3.620e+08           3rd Qu.:1.064e+07                           
 Max.   :5.761e+10           Max.   :1.494e+09                           
 NA's   :14                  NA's   :14                                  
 Projected_Pension_Contribution Net_OPEB_Liability_or_Asset
 Min.   :    38509              Min.   :2.917e+04          
 1st Qu.:  1410980              1st Qu.:2.302e+06          
 Median :  4653424              Median :6.965e+06          
 Mean   : 13601756              Mean   :4.792e+07          
 3rd Qu.: 14650576              3rd Qu.:2.689e+07          
 Max.   :239393864              Max.   :3.903e+09          
 NA's   :25                     NA's   :100                </code></pre>
</div>
</div>
</section>
<section id="missing-values" class="level3">
<h3 class="anchored" data-anchor-id="missing-values">Missing Values</h3>
<p>Consider using only complete objects or use mean and mode imputation when modeling</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing values per variable</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>missing.values <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="at">Missing_Count =</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>missing.values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                          Missing_Count
City_Name                                                                             0
Overall_Rank                                                                          0
General_Fund_Reserves_Rank                                                            0
Debt_Burden_Rank                                                                      0
Liquidity_Rank                                                                        0
Revenue_Trends_Rank                                                                   0
Pension_Obligations_Rank                                                              0
Pension_Funding_Rank                                                                  0
Pension_Costs_Rank                                                                    0
Future_Pension_Costs_Rank                                                             0
OPEB_Obligations_Rank                                                                 0
OPEB_Funding_Rank                                                                     0
Overall_Risk                                                                          0
General_Fund_Reserves_Risk                                                            0
Debt_Burden_Risk                                                                      0
Liquidity_Risk                                                                        0
Revenue_Trends_Risk                                                                   0
Pension_Obligations_Risk                                                              0
Pension_Funding_Risk                                                                  0
Pension_Costs_Risk                                                                    0
Future_Pension_Costs_Risk                                                             0
OPEB_Obligations_Risk                                                                 0
OPEB_Funding_Risk                                                                     0
Overall_Points                                                                        0
General_Fund_Reserves_Points                                                          0
Debt_Burden_Points                                                                    0
Liquidity_Points                                                                      0
Revenue_Trends_Points                                                                 0
Pension_Obligations_Points                                                            0
Pension_Funding_Points                                                                0
Pension_Costs_Points                                                                  0
Future_Pension_Costs_Points                                                           0
OPEB_Obligations_Points                                                               0
OPEB_Funding_Points                                                                   0
General_Fund_Reserves_Ratio                                                           1
Debt_Burden_Ratio                                                                     1
Liquidity_Ratio                                                                       1
Revenue_Trends_Ratio                                                                  1
Pension_Obligations_Ratio                                                            14
Pension_Funding_Ratio                                                                14
Pension_Costs_Ratio                                                                  14
Future_Pension_Costs_Ratio                                                           25
OPEB_Obligations_Ratio                                                               77
OPEB_Funding_Ratio                                                                   77
Population                                                                            0
Unemployment_rate                                                                     9
General_Fund_Cash_and_Investments                                                     1
General_Fund_Liabilities                                                              1
Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations             1
Government_Wide_Revenue                                                               1
Change_GF_Unrestricted_Fund_Balances                                                  1
GF_Unrestricted_Fund_Balances                                                         1
GF_Expenditures_Transfers_Out                                                         1
GF_Unrestricted_FB_PY_PY                                                              2
GF_Unrestricted_FB_PY                                                                 1
GF_Unrestricted_FB_CY                                                                 1
GF_Rev_PY_PY                                                                          2
GF_Rev_PY                                                                             1
GF_Rev_CY                                                                             1
Net_Pension_Liability_or_Asset                                                       14
Pension_Related_Debt                                                                 14
Pension_Assets                                                                       14
Accrued_Pension_Liabilities                                                          14
Actuarially_Determined_Pension_Contributions                                         14
Projected_Pension_Contribution                                                       25
Net_OPEB_Liability_or_Asset                                                         100</code></pre>
</div>
</div>
</section>
<section id="boxplots-points-and-risks" class="level3">
<h3 class="anchored" data-anchor-id="boxplots-points-and-risks">Boxplots: Points and Risks</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Points by Risk Boxplots</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cat <span class="ot">&lt;-</span> <span class="dv">13</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>num <span class="ot">&lt;-</span> <span class="dv">24</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>){</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Boxplot</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  cat_col <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[cat] <span class="co"># Categorical variable</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  num_col <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[num] <span class="co"># Numeric variable</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  y_min <span class="ot">&lt;-</span> <span class="fu">min</span>(data[[num_col]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  y_max <span class="ot">&lt;-</span> <span class="fu">max</span>(data[[num_col]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  y_margin <span class="ot">&lt;-</span> (y_max <span class="sc">-</span> y_min) <span class="sc">*</span> <span class="fl">0.1</span> <span class="co"># Add 10% margin for better centering</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    data, </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes_string</span>(<span class="at">x =</span> cat_col, <span class="at">y =</span> num_col, <span class="at">fill =</span> cat_col)) <span class="sc">+</span> </span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="co"># Hide outliers for better centering</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(y_min <span class="sc">-</span> y_margin, y_max <span class="sc">+</span> y_margin)) <span class="sc">+</span> <span class="co"># Adjust limits dynamically</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Boxplot of"</span>, num_col, <span class="st">"by"</span>, cat_col),</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> cat_col,</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> num_col,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> cat_col) <span class="sc">+</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print the plot</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p)</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>  cat <span class="ot">&lt;-</span> cat <span class="sc">+</span><span class="dv">1</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>  num <span class="ot">&lt;-</span> num <span class="sc">+</span><span class="dv">1</span></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-8-11.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For each risk category, getting higher points means lower risk in the specific category. However, due to different range of points in different categories overall points are not meaningfully corresponding to overall risk level for the local governments.</p>
</section>
<section id="boxplots-ratio-and-risks" class="level3">
<h3 class="anchored" data-anchor-id="boxplots-ratio-and-risks">Boxplots: Ratio and Risks</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ratio by Risk</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>cat <span class="ot">&lt;-</span> <span class="dv">14</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>num <span class="ot">&lt;-</span> <span class="dv">35</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>){</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Boxplot</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  cat_col <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[cat] <span class="co"># Categorical variable</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  num_col <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[num] <span class="co"># Numeric variable</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  y_min <span class="ot">&lt;-</span> <span class="fu">min</span>(data[[num_col]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  y_max <span class="ot">&lt;-</span> <span class="fu">max</span>(data[[num_col]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  y_margin <span class="ot">&lt;-</span> (y_max <span class="sc">-</span> y_min) <span class="sc">*</span> <span class="fl">0.1</span> <span class="co"># Add 10% margin for better centering</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes_string</span>(<span class="at">x =</span> cat_col, <span class="at">y =</span> num_col, <span class="at">fill =</span> cat_col)) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span> <span class="co"># Hide outliers for better centering</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(y_min <span class="sc">-</span> y_margin, y_max <span class="sc">+</span> y_margin)) <span class="sc">+</span> <span class="co"># Adjust limits dynamically</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Boxplot of"</span>, num_col, <span class="st">"by"</span>, cat_col),</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> cat_col,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> num_col,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> cat_col) <span class="sc">+</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print the plot</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>  cat <span class="ot">&lt;-</span> cat <span class="sc">+</span><span class="dv">1</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>  num <span class="ot">&lt;-</span> num <span class="sc">+</span><span class="dv">1</span></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 14 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 25 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 77 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 77 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-9-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ratio can potentially be either positively or negatively related to their specific Risks.</p>
</section>
<section id="mean-and-mode-imputation" class="level3">
<h3 class="anchored" data-anchor-id="mean-and-mode-imputation">Mean and mode imputation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Impute missing values with column means</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>data_imputed <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.), <span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), .)))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>missing_counts <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Missing values per variable after imputation</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>missing.imputed <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Missing_Count =</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data_imputed))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(missing.imputed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="histogram-of-risk-levels" class="level3">
<h3 class="anchored" data-anchor-id="histogram-of-risk-levels">Histogram of Risk Levels</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of Risk Levels by Variables</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>cat <span class="ot">&lt;-</span> <span class="dv">13</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>) {</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  cat_col <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[cat] <span class="co"># Categorical variable</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes_string</span>(<span class="at">x =</span> cat_col, <span class="at">fill =</span> cat_col)) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Histogram of Risk Levels for"</span>, cat_col),</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> cat_col,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"Risk Level"</span>) <span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  cat <span class="ot">&lt;-</span> cat <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-12-11.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="statistic-modeling" class="level2">
<h2 class="anchored" data-anchor-id="statistic-modeling">2. Statistic Modeling:</h2>
<section id="ordinal-logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="ordinal-logistic-regression">Ordinal logistic regression:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'MASS' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ordinal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ordinal' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ordinal'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    slice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>ordinal_model <span class="ot">&lt;-</span> <span class="fu">clm</span>(Overall_Risk <span class="sc">~</span> General_Fund_Reserves_Ratio <span class="sc">+</span> Debt_Burden_Ratio <span class="sc">+</span> Liquidity_Ratio <span class="sc">+</span> Revenue_Trends_Ratio <span class="sc">+</span> Pension_Obligations_Ratio <span class="sc">+</span> Pension_Funding_Ratio <span class="sc">+</span> Pension_Costs_Ratio <span class="sc">+</span> Future_Pension_Costs_Ratio <span class="sc">+</span> OPEB_Obligations_Ratio <span class="sc">+</span> OPEB_Funding_Ratio,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_imputed,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ordinal_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: 
Overall_Risk ~ General_Fund_Reserves_Ratio + Debt_Burden_Ratio + Liquidity_Ratio + Revenue_Trends_Ratio + Pension_Obligations_Ratio + Pension_Funding_Ratio + Pension_Costs_Ratio + Future_Pension_Costs_Ratio + OPEB_Obligations_Ratio + OPEB_Funding_Ratio
data:    data_imputed

 link  threshold nobs logLik  AIC    niter max.grad cond.H 
 logit flexible  423  -267.17 558.34 7(0)  1.50e-09 4.7e+05

Coefficients:
                            Estimate Std. Error z value Pr(&gt;|z|)    
General_Fund_Reserves_Ratio -0.24111    0.08069  -2.988  0.00281 ** 
Debt_Burden_Ratio            0.58626    0.21870   2.681  0.00735 ** 
Liquidity_Ratio             -0.06083    0.01540  -3.950  7.8e-05 ***
Revenue_Trends_Ratio        -2.20938    1.71059  -1.292  0.19650    
Pension_Obligations_Ratio    1.16436    0.56056   2.077  0.03779 *  
Pension_Funding_Ratio        1.74199    1.57109   1.109  0.26753    
Pension_Costs_Ratio         -5.52329    6.08241  -0.908  0.36384    
Future_Pension_Costs_Ratio  14.62631    5.26400   2.779  0.00546 ** 
OPEB_Obligations_Ratio      -0.02841    0.70131  -0.041  0.96769    
OPEB_Funding_Ratio          -1.03841    0.36949  -2.810  0.00495 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
              Estimate Std. Error z value
LOW|MODERATE    -2.319      1.425  -1.627
MODERATE|HIGH    2.458      1.380   1.781</code></pre>
</div>
</div>
</section>
</section>
<section id="predictive-modeling" class="level2">
<h2 class="anchored" data-anchor-id="predictive-modeling">3. Predictive Modeling:</h2>
<section id="random-forests" class="level3">
<h3 class="anchored" data-anchor-id="random-forests">Random Forests:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'randomForest' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type rfNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'randomForest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gbm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gbm' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded gbm 2.2.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>This version of gbm is no longer under development. Consider transitioning to gbm3, https://github.com/gbm-developers/gbm3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'caret' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>selected_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Overall_Risk"</span>, <span class="st">"General_Fund_Reserves_Ratio"</span>, <span class="st">"Debt_Burden_Ratio"</span>, </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Liquidity_Ratio"</span>, <span class="st">"Revenue_Trends_Ratio"</span>, <span class="st">"Pension_Obligations_Ratio"</span>, </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Pension_Funding_Ratio"</span>, <span class="st">"Pension_Costs_Ratio"</span>, </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Future_Pension_Costs_Ratio"</span>, <span class="st">"OPEB_Obligations_Ratio"</span>, <span class="st">"OPEB_Funding_Ratio"</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>data_selected <span class="ot">&lt;-</span> data_imputed[, selected_vars]</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data into training (70%) and testing (30%) sets</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(data_selected<span class="sc">$</span>Overall_Risk, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> data_selected[train_index, ]</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> data_selected[<span class="sc">-</span>train_index, ]</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Overall_Risk <span class="sc">~</span> ., <span class="at">data =</span> train_data, </span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mtry =</span> <span class="fu">ncol</span>(train_data) <span class="sc">-</span> <span class="dv">1</span>, <span class="at">importance =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rf_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = Overall_Risk ~ ., data = train_data, mtry = ncol(train_data) -      1, importance = TRUE) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 10

        OOB estimate of  error rate: 12.42%
Confusion matrix:
         LOW MODERATE HIGH class.error
LOW        3        1    5   0.6666667
MODERATE   0      135   16   0.1059603
HIGH       3       12  123   0.1086957</code></pre>
</div>
</div>
<p>Here we fit a Random Forest Model using 10 splits (all predictors). Looking at the results, we see an OOB error rate of 12.42% which means that the model misclassifies about 12.42% total observations. Furthermore, we can see that the Random Forest model tends to have a harder time predicted for the class “LOW.” While the OOB error rate is relatively low, the class.error for LOW is extremely high.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable Importance Plot</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(rf_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   LOW  MODERATE      HIGH MeanDecreaseAccuracy
General_Fund_Reserves_Ratio 17.5817197 60.107365 78.766294            93.194022
Debt_Burden_Ratio            1.0786688  8.128296  9.917937            12.218631
Liquidity_Ratio             11.6225670  1.747423 14.461770            16.173105
Revenue_Trends_Ratio         1.2192035 -1.619935 -1.911778            -2.209593
Pension_Obligations_Ratio   11.2341174 23.078055 24.191498            33.094629
Pension_Funding_Ratio        4.0108439  6.602884  6.661010             9.119146
Pension_Costs_Ratio          1.6470805  9.396006  3.779072            10.103250
Future_Pension_Costs_Ratio   7.5146768 10.120949  7.740986            13.408256
OPEB_Obligations_Ratio       1.8499933 11.447187  1.947810             9.984454
OPEB_Funding_Ratio           0.3245529  8.479432 13.106371            14.777234
                            MeanDecreaseGini
General_Fund_Reserves_Ratio        96.359249
Debt_Burden_Ratio                   7.400525
Liquidity_Ratio                     9.142545
Revenue_Trends_Ratio                2.940298
Pension_Obligations_Ratio          17.871268
Pension_Funding_Ratio               4.320126
Pension_Costs_Ratio                 2.571313
Future_Pension_Costs_Ratio          5.940656
OPEB_Obligations_Ratio              5.000233
OPEB_Funding_Ratio                  5.173426</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(rf_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Variable importance for the Random Forest model was determined through: 1) Mean Decrease in Accuracy, and 2) Mean Decrease in Gini Impurity.</p>
<p>The first evaluates the model’s accuracy by permuting each variable while the second shows how impurity in tree splits are reduced based on a variable’s significance. In both these charts, general fund reserves has the greatest value. In other words, the general fund reserve is a significant contributor to predicting the overall risk.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion Matrix and Accuracy</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>rf_conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(rf_predictions, test_data<span class="sc">$</span>Overall_Risk)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rf_conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction LOW MODERATE HIGH
  LOW        2        0    0
  MODERATE   0       59    2
  HIGH       1        5   56

Overall Statistics
                                         
               Accuracy : 0.936          
                 95% CI : (0.8778, 0.972)
    No Information Rate : 0.512          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
                                         
                  Kappa : 0.8768         
                                         
 Mcnemar's Test P-Value : NA             

Statistics by Class:

                     Class: LOW Class: MODERATE Class: HIGH
Sensitivity              0.6667          0.9219      0.9655
Specificity              1.0000          0.9672      0.9104
Pos Pred Value           1.0000          0.9672      0.9032
Neg Pred Value           0.9919          0.9219      0.9683
Prevalence               0.0240          0.5120      0.4640
Detection Rate           0.0160          0.4720      0.4480
Detection Prevalence     0.0160          0.4880      0.4960
Balanced Accuracy        0.8333          0.9445      0.9380</code></pre>
</div>
</div>
<p>Using our Random Forest model based on our training data, the prediction accuracy relatively high at 93.6%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="do">### XGBOOST MODEL </span><span class="al">###</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data for XGBoost</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>selected_vars_xg <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Overall_Risk"</span>, <span class="st">"General_Fund_Reserves_Ratio"</span>, <span class="st">"Debt_Burden_Ratio"</span>, </span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Liquidity_Ratio"</span>, <span class="st">"Revenue_Trends_Ratio"</span>, <span class="st">"Pension_Obligations_Ratio"</span>, </span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Pension_Funding_Ratio"</span>, <span class="st">"Pension_Costs_Ratio"</span>, </span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Future_Pension_Costs_Ratio"</span>, <span class="st">"OPEB_Obligations_Ratio"</span>, <span class="st">"OPEB_Funding_Ratio"</span>)</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>data_selected_xg <span class="ot">&lt;-</span> data_imputed[, selected_vars_xg]</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>train_index_xg <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(data_selected_xg<span class="sc">$</span>Overall_Risk, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>train_data_xg <span class="ot">&lt;-</span> data_selected[train_index_xg, ]</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>test_data_xg <span class="ot">&lt;-</span> data_selected[<span class="sc">-</span>train_index_xg, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(caret)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(xgboost)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>train_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)  <span class="co"># 10-fold CV</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Train XGBoost model</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>xgb_model <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  Overall_Risk <span class="sc">~</span> ., </span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_data_xg, </span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"xgbTree"</span>, </span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> train_control,</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="cn">FALSE</span>,</span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbosity =</span> <span class="dv">0</span></span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Print model summary</span></span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(xgb_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>eXtreme Gradient Boosting 

298 samples
 10 predictor
  3 classes: 'LOW', 'MODERATE', 'HIGH' 

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 269, 269, 268, 268, 269, 268, ... 
Resampling results across tuning parameters:

  eta  max_depth  colsample_bytree  subsample  nrounds  Accuracy   Kappa    
  0.3  1          0.6               0.50        50      0.8894105  0.7865674
  0.3  1          0.6               0.50       100      0.9063070  0.8200302
  0.3  1          0.6               0.50       150      0.9028587  0.8130274
  0.3  1          0.6               0.75        50      0.8960771  0.7985020
  0.3  1          0.6               0.75       100      0.8997479  0.8065433
  0.3  1          0.6               0.75       150      0.9028587  0.8142615
  0.3  1          0.6               1.00        50      0.8827364  0.7726474
  0.3  1          0.6               1.00       100      0.8894030  0.7867612
  0.3  1          0.6               1.00       150      0.8896329  0.7884062
  0.3  1          0.8               0.50        50      0.8859622  0.7794157
  0.3  1          0.8               0.50       100      0.9026437  0.8119677
  0.3  1          0.8               0.50       150      0.9095402  0.8259553
  0.3  1          0.8               0.75        50      0.8859622  0.7796084
  0.3  1          0.8               0.75       100      0.8996403  0.8067785
  0.3  1          0.8               0.75       150      0.9096403  0.8266797
  0.3  1          0.8               1.00        50      0.8727364  0.7527284
  0.3  1          0.8               1.00       100      0.8860697  0.7802539
  0.3  1          0.8               1.00       150      0.8795180  0.7695893
  0.3  2          0.6               0.50        50      0.9158621  0.8368408
  0.3  2          0.6               0.50       100      0.9126363  0.8312833
  0.3  2          0.6               0.50       150      0.9159696  0.8377627
  0.3  2          0.6               0.75        50      0.9126363  0.8312135
  0.3  2          0.6               0.75       100      0.9094179  0.8256865
  0.3  2          0.6               0.75       150      0.9129737  0.8334898
  0.3  2          0.6               1.00        50      0.8994179  0.8062013
  0.3  2          0.6               1.00       100      0.9059770  0.8184353
  0.3  2          0.6               1.00       150      0.9125287  0.8312164
  0.3  2          0.8               0.50        50      0.9093103  0.8247460
  0.3  2          0.8               0.50       100      0.9260920  0.8571951
  0.3  2          0.8               0.50       150      0.9227586  0.8510944
  0.3  2          0.8               0.75        50      0.9058547  0.8180022
  0.3  2          0.8               0.75       100      0.9195328  0.8448847
  0.3  2          0.8               0.75       150      0.9094179  0.8255420
  0.3  2          0.8               1.00        50      0.8959696  0.7994848
  0.3  2          0.8               1.00       100      0.9094253  0.8254197
  0.3  2          0.8               1.00       150      0.9125287  0.8314302
  0.3  3          0.6               0.50        50      0.9263144  0.8580679
  0.3  3          0.6               0.50       100      0.9163070  0.8385977
  0.3  3          0.6               0.50       150      0.9128587  0.8325332
  0.3  3          0.6               0.75        50      0.9028587  0.8132026
  0.3  3          0.6               0.75       100      0.9027438  0.8132045
  0.3  3          0.6               0.75       150      0.9094105  0.8261078
  0.3  3          0.6               1.00        50      0.9191954  0.8440368
  0.3  3          0.6               1.00       100      0.9259770  0.8577046
  0.3  3          0.6               1.00       150      0.9226437  0.8515850
  0.3  3          0.8               0.50        50      0.9194179  0.8453759
  0.3  3          0.8               0.50       100      0.9263144  0.8590132
  0.3  3          0.8               0.50       150      0.9296552  0.8649878
  0.3  3          0.8               0.75        50      0.9093029  0.8258588
  0.3  3          0.8               0.75       100      0.9094179  0.8262194
  0.3  3          0.8               0.75       150      0.9128661  0.8331406
  0.3  3          0.8               1.00        50      0.8889655  0.7855703
  0.3  3          0.8               1.00       100      0.9093103  0.8259123
  0.3  3          0.8               1.00       150      0.9059770  0.8198518
  0.4  1          0.6               0.50        50      0.8994179  0.8051958
  0.4  1          0.6               0.50       100      0.9093029  0.8256242
  0.4  1          0.6               0.50       150      0.8927438  0.7944480
  0.4  1          0.6               0.75        50      0.8960771  0.7981854
  0.4  1          0.6               0.75       100      0.9098628  0.8269722
  0.4  1          0.6               0.75       150      0.9097553  0.8270636
  0.4  1          0.6               1.00        50      0.8828513  0.7731589
  0.4  1          0.6               1.00       100      0.8996329  0.8061801
  0.4  1          0.6               1.00       150      0.8962996  0.8010116
  0.4  1          0.8               0.50        50      0.9061921  0.8194954
  0.4  1          0.8               0.50       100      0.9228661  0.8513439
  0.4  1          0.8               0.50       150      0.9227512  0.8505528
  0.4  1          0.8               0.75        50      0.8996403  0.8061267
  0.4  1          0.8               0.75       100      0.9129737  0.8325301
  0.4  1          0.8               0.75       150      0.9097553  0.8261552
  0.4  1          0.8               1.00        50      0.8892955  0.7853666
  0.4  1          0.8               1.00       100      0.8962996  0.7997773
  0.4  1          0.8               1.00       150      0.8896329  0.7893759
  0.4  2          0.6               0.50        50      0.9061995  0.8188723
  0.4  2          0.6               0.50       100      0.9197627  0.8457372
  0.4  2          0.6               0.50       150      0.9230960  0.8521505
  0.4  2          0.6               0.75        50      0.8927438  0.7929293
  0.4  2          0.6               0.75       100      0.9059696  0.8186881
  0.4  2          0.6               0.75       150      0.9195328  0.8454352
  0.4  2          0.6               1.00        50      0.9026437  0.8130443
  0.4  2          0.6               1.00       100      0.9260920  0.8578545
  0.4  2          0.6               1.00       150      0.9058547  0.8201034
  0.4  2          0.8               0.50        50      0.9130886  0.8326291
  0.4  2          0.8               0.50       100      0.9165369  0.8400269
  0.4  2          0.8               0.50       150      0.9130886  0.8331662
  0.4  2          0.8               0.75        50      0.9126363  0.8311069
  0.4  2          0.8               0.75       100      0.9093029  0.8255653
  0.4  2          0.8               0.75       150      0.9126363  0.8319615
  0.4  2          0.8               1.00        50      0.9060845  0.8194710
  0.4  2          0.8               1.00       100      0.9128661  0.8329472
  0.4  2          0.8               1.00       150      0.9094179  0.8265390
  0.4  3          0.6               0.50        50      0.9128587  0.8325461
  0.4  3          0.6               0.50       100      0.9026288  0.8124190
  0.4  3          0.6               0.50       150      0.9060771  0.8191629
  0.4  3          0.6               0.75        50      0.9196403  0.8456536
  0.4  3          0.6               0.75       100      0.9161921  0.8389578
  0.4  3          0.6               0.75       150      0.9127438  0.8320694
  0.4  3          0.6               1.00        50      0.9090805  0.8247751
  0.4  3          0.6               1.00       100      0.9159770  0.8380401
  0.4  3          0.6               1.00       150      0.9127512  0.8320900
  0.4  3          0.8               0.50        50      0.9126363  0.8313815
  0.4  3          0.8               0.50       100      0.9160845  0.8380326
  0.4  3          0.8               0.50       150      0.9194179  0.8444014
  0.4  3          0.8               0.75        50      0.9160845  0.8384068
  0.4  3          0.8               0.75       100      0.9195328  0.8451096
  0.4  3          0.8               0.75       150      0.9195328  0.8453370
  0.4  3          0.8               1.00        50      0.8956322  0.7996097
  0.4  3          0.8               1.00       100      0.9025287  0.8127853
  0.4  3          0.8               1.00       150      0.8991954  0.8067249

Tuning parameter 'gamma' was held constant at a value of 0
Tuning
 parameter 'min_child_weight' was held constant at a value of 1
Accuracy was used to select the optimal model using the largest value.
The final values used for the model were nrounds = 150, max_depth = 3, eta
 = 0.3, gamma = 0, colsample_bytree = 0.8, min_child_weight = 1 and subsample
 = 0.5.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>xgb_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(xgb_model, <span class="at">newdata =</span> test_data_xg)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion Matrix and Accuracy</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>xgb_conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(xgb_predictions, test_data_xg<span class="sc">$</span>Overall_Risk)</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(xgb_conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction LOW MODERATE HIGH
  LOW        2        0    0
  MODERATE   0       59    4
  HIGH       1        5   54

Overall Statistics
                                         
               Accuracy : 0.92           
                 95% CI : (0.8578, 0.961)
    No Information Rate : 0.512          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
                                         
                  Kappa : 0.8458         
                                         
 Mcnemar's Test P-Value : NA             

Statistics by Class:

                     Class: LOW Class: MODERATE Class: HIGH
Sensitivity              0.6667          0.9219      0.9310
Specificity              1.0000          0.9344      0.9104
Pos Pred Value           1.0000          0.9365      0.9000
Neg Pred Value           0.9919          0.9194      0.9385
Prevalence               0.0240          0.5120      0.4640
Detection Rate           0.0160          0.4720      0.4320
Detection Prevalence     0.0160          0.5040      0.4800
Balanced Accuracy        0.8333          0.9282      0.9207</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>feature_importance <span class="ot">&lt;-</span> <span class="fu">varImp</span>(xgb_model, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot importance</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(feature_importance, <span class="at">main =</span> <span class="st">"Feature Importance in XGBoost Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="stats140xp_project_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We created an eXtreme Gradient Boosting (XGBoost) predictive model. The XGBoost model was trained using 10-fold cross validation and applied to the training dataset. The model was tuned using hyperparameters nrounds = 150, max_depth = 3, eta = 0.3, gamma = 0, colsample_bytree = 0.8, min_child_weight = 1 and subsample = 0.5.</p>
<p>Similar to the Random Forest model, the XGBoost model also performed relatively well achieving a prediction accuracy of 92%. Furthermore, looking at the statistics by class, we see the “LOW” class has the lowest prediction accuracy with only 2 out of 3 cases being correctly classified. On the other hand, levels like “MODERATE” and “HIGH” had a much higher classification rate. These results look very similar to our Random Forest model.</p>
<p>Furthermore, while looking at the feature importance plot, we see similar results of general fund reserves being a key contributor for risk classification.</p>
<p>However, unlike the Random Forest model, the XGBoost model is computationally expensive and even achieved a slightly lower accuracy rate. Due to its complexity and slower learning method of fitting each decision tree sequentially, there is a possibility that our data has been overfit.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>