project:
  type: website

website:
  title: "Nicole Lee"
  navbar:
    right:
      - href: index.qmd
        text: Landing Page
      - about.qmd

format:
  html:
    theme: 
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

