{
  "hash": "670207990385f97c1903b9ffba21bd72",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assessing Fiscal Risk and Financial Stability\"\nauthor: \"Nicole Lee\"\ndescription: \"Leveraged machine learning algorithms like ordinal logistic regression and decision trees to achieving 92% prediction accuracy. Visualized key trends to support strategic recommendations for early policy intervention.\"\ndate: \"2025-03-07\"\n---\n\n\n\n\n\nDownload the [Report](/stats_140xp_paper.pdf)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\ndata <- read.csv(\"C:/Users/nicol/Downloads/fy2019-20 (1).csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert risk columns (columns 13:23) into factors\n# Standardize levels: ALL CAPS\ndata[,13] <- as.factor(data[,13])\nlevels(data[,13])<- c(\"LOW\", \"MODERATE\", \"HIGH\")\n\nfor (i in 0:9){\n  data[,13+i] <- factor(data[,13+i], order=TRUE, levels = c(\"LOW\", \"MODERATE\", \"HIGH\"))\n}\n```\n:::\n\n\n\n\n\nColumn num, Items 1: City Names 2-12: Rank 13-23: Risk 24-34: Points 35-44: Ratio 45-66: Other Numeric Data\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Numeric Items\npoints <- data[, 24:34]\nratio <- data[, 35:44]\nnumeric <- data[, 45:66]\n```\n:::\n\n\n\n\n\n# 1. Exploratory Data Analysis:\n\n## Correlation Analysis:\n\nConsider take out some of the highly correlated variables when modeling\n\n### Correlation Analysis Using Ratios:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correlation\nratio_corr <- cor(ratio, use = \"complete.obs\")\nratio_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            General_Fund_Reserves_Ratio Debt_Burden_Ratio\nGeneral_Fund_Reserves_Ratio                  1.00000000       0.005155050\nDebt_Burden_Ratio                            0.00515505       1.000000000\nLiquidity_Ratio                              0.33811237      -0.017499614\nRevenue_Trends_Ratio                         0.04393613       0.046310907\nPension_Obligations_Ratio                   -0.15747725       0.045011789\nPension_Funding_Ratio                        0.13377685      -0.101198033\nPension_Costs_Ratio                         -0.20640017       0.018499816\nFuture_Pension_Costs_Ratio                  -0.18872225       0.009290444\nOPEB_Obligations_Ratio                      -0.06737789       0.068615098\nOPEB_Funding_Ratio                           0.19531425      -0.093349356\n                            Liquidity_Ratio Revenue_Trends_Ratio\nGeneral_Fund_Reserves_Ratio     0.338112370          0.043936126\nDebt_Burden_Ratio              -0.017499614          0.046310907\nLiquidity_Ratio                 1.000000000         -0.001968421\nRevenue_Trends_Ratio           -0.001968421          1.000000000\nPension_Obligations_Ratio      -0.220281682         -0.039903799\nPension_Funding_Ratio           0.157083948         -0.077086569\nPension_Costs_Ratio            -0.214179610         -0.019395935\nFuture_Pension_Costs_Ratio     -0.209027927         -0.049089502\nOPEB_Obligations_Ratio         -0.084776650         -0.046797256\nOPEB_Funding_Ratio              0.255285406         -0.107584591\n                            Pension_Obligations_Ratio Pension_Funding_Ratio\nGeneral_Fund_Reserves_Ratio               -0.15747725            0.13377685\nDebt_Burden_Ratio                          0.04501179           -0.10119803\nLiquidity_Ratio                           -0.22028168            0.15708395\nRevenue_Trends_Ratio                      -0.03990380           -0.07708657\nPension_Obligations_Ratio                  1.00000000           -0.28673182\nPension_Funding_Ratio                     -0.28673182            1.00000000\nPension_Costs_Ratio                        0.81012988           -0.42052344\nFuture_Pension_Costs_Ratio                 0.79928352           -0.57846759\nOPEB_Obligations_Ratio                     0.38775799           -0.06788278\nOPEB_Funding_Ratio                        -0.25837661            0.15871182\n                            Pension_Costs_Ratio Future_Pension_Costs_Ratio\nGeneral_Fund_Reserves_Ratio         -0.20640017               -0.188722254\nDebt_Burden_Ratio                    0.01849982                0.009290444\nLiquidity_Ratio                     -0.21417961               -0.209027927\nRevenue_Trends_Ratio                -0.01939593               -0.049089502\nPension_Obligations_Ratio            0.81012988                0.799283517\nPension_Funding_Ratio               -0.42052344               -0.578467593\nPension_Costs_Ratio                  1.00000000                0.851604010\nFuture_Pension_Costs_Ratio           0.85160401                1.000000000\nOPEB_Obligations_Ratio               0.27051688                0.278913672\nOPEB_Funding_Ratio                  -0.20429957               -0.209207470\n                            OPEB_Obligations_Ratio OPEB_Funding_Ratio\nGeneral_Fund_Reserves_Ratio            -0.06737789         0.19531425\nDebt_Burden_Ratio                       0.06861510        -0.09334936\nLiquidity_Ratio                        -0.08477665         0.25528541\nRevenue_Trends_Ratio                   -0.04679726        -0.10758459\nPension_Obligations_Ratio               0.38775799        -0.25837661\nPension_Funding_Ratio                  -0.06788278         0.15871182\nPension_Costs_Ratio                     0.27051688        -0.20429957\nFuture_Pension_Costs_Ratio              0.27891367        -0.20920747\nOPEB_Obligations_Ratio                  1.00000000        -0.38722256\nOPEB_Funding_Ratio                     -0.38722256         1.00000000\n```\n\n\n:::\n\n```{.r .cell-code}\nheatmap(ratio_corr)\n```\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Correlation Analysis Using Other Numeric Variables:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correlation\nnumeric_corr <- cor(numeric, use = \"complete.obs\")\nnumeric_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                           Population\nPopulation                                                                 1.00000000\nUnemployment_rate                                                          0.10458595\nGeneral_Fund_Cash_and_Investments                                          0.57453187\nGeneral_Fund_Liabilities                                                   0.60112910\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.67300823\nGovernment_Wide_Revenue                                                    0.83252773\nChange_GF_Unrestricted_Fund_Balances                                      -0.05122791\nGF_Unrestricted_Fund_Balances                                              0.59262806\nGF_Expenditures_Transfers_Out                                              0.83192423\nGF_Unrestricted_FB_PY_PY                                                   0.53903592\nGF_Unrestricted_FB_PY                                                      0.60847563\nGF_Unrestricted_FB_CY                                                      0.59262806\nGF_Rev_PY_PY                                                               0.82733012\nGF_Rev_PY                                                                  0.82976920\nGF_Rev_CY                                                                  0.84695900\nNet_Pension_Liability_or_Asset                                             0.81784437\nPension_Related_Debt                                                       0.32108175\nPension_Assets                                                             0.82653615\nAccrued_Pension_Liabilities                                                0.82658650\nActuarially_Determined_Pension_Contributions                               0.81326159\nProjected_Pension_Contribution                                             0.81969997\nNet_OPEB_Liability_or_Asset                                                0.54888106\n                                                                          Unemployment_rate\nPopulation                                                                     0.1045859539\nUnemployment_rate                                                              1.0000000000\nGeneral_Fund_Cash_and_Investments                                             -0.0542933134\nGeneral_Fund_Liabilities                                                       0.0212190349\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations      0.0386830382\nGovernment_Wide_Revenue                                                        0.0039532113\nChange_GF_Unrestricted_Fund_Balances                                          -0.0562638842\nGF_Unrestricted_Fund_Balances                                                 -0.0648134571\nGF_Expenditures_Transfers_Out                                                  0.0098504456\nGF_Unrestricted_FB_PY_PY                                                      -0.0586534938\nGF_Unrestricted_FB_PY                                                         -0.0600948138\nGF_Unrestricted_FB_CY                                                         -0.0648134571\nGF_Rev_PY_PY                                                                   0.0044085224\nGF_Rev_PY                                                                      0.0004024498\nGF_Rev_CY                                                                      0.0031155336\nNet_Pension_Liability_or_Asset                                                 0.0220704718\nPension_Related_Debt                                                           0.0969817437\nPension_Assets                                                                 0.0436271464\nAccrued_Pension_Liabilities                                                    0.0345197300\nActuarially_Determined_Pension_Contributions                                   0.0183949195\nProjected_Pension_Contribution                                                 0.0153072919\nNet_OPEB_Liability_or_Asset                                                    0.0708310557\n                                                                          General_Fund_Cash_and_Investments\nPopulation                                                                                       0.57453187\nUnemployment_rate                                                                               -0.05429331\nGeneral_Fund_Cash_and_Investments                                                                1.00000000\nGeneral_Fund_Liabilities                                                                         0.82028822\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                        0.40020185\nGovernment_Wide_Revenue                                                                          0.66020381\nChange_GF_Unrestricted_Fund_Balances                                                            -0.04356678\nGF_Unrestricted_Fund_Balances                                                                    0.81081400\nGF_Expenditures_Transfers_Out                                                                    0.79730538\nGF_Unrestricted_FB_PY_PY                                                                         0.84175499\nGF_Unrestricted_FB_PY                                                                            0.88359469\nGF_Unrestricted_FB_CY                                                                            0.81081400\nGF_Rev_PY_PY                                                                                     0.81259230\nGF_Rev_PY                                                                                        0.81246633\nGF_Rev_CY                                                                                        0.80984833\nNet_Pension_Liability_or_Asset                                                                   0.70085542\nPension_Related_Debt                                                                             0.34136911\nPension_Assets                                                                                   0.67024018\nAccrued_Pension_Liabilities                                                                      0.69290692\nActuarially_Determined_Pension_Contributions                                                     0.74376035\nProjected_Pension_Contribution                                                                   0.69843112\nNet_OPEB_Liability_or_Asset                                                                      0.62947284\n                                                                          General_Fund_Liabilities\nPopulation                                                                              0.60112910\nUnemployment_rate                                                                       0.02121903\nGeneral_Fund_Cash_and_Investments                                                       0.82028822\nGeneral_Fund_Liabilities                                                                1.00000000\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations               0.51213626\nGovernment_Wide_Revenue                                                                 0.68284422\nChange_GF_Unrestricted_Fund_Balances                                                   -0.02621429\nGF_Unrestricted_Fund_Balances                                                           0.49972955\nGF_Expenditures_Transfers_Out                                                           0.82519244\nGF_Unrestricted_FB_PY_PY                                                                0.54698719\nGF_Unrestricted_FB_PY                                                                   0.58521821\nGF_Unrestricted_FB_CY                                                                   0.49972955\nGF_Rev_PY_PY                                                                            0.83150876\nGF_Rev_PY                                                                               0.82761768\nGF_Rev_CY                                                                               0.82464213\nNet_Pension_Liability_or_Asset                                                          0.78867980\nPension_Related_Debt                                                                    0.44621468\nPension_Assets                                                                          0.75632879\nAccrued_Pension_Liabilities                                                             0.78147285\nActuarially_Determined_Pension_Contributions                                            0.83237643\nProjected_Pension_Contribution                                                          0.77097538\nNet_OPEB_Liability_or_Asset                                                             0.76640255\n                                                                          Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations\nPopulation                                                                                                                               0.67300823\nUnemployment_rate                                                                                                                        0.03868304\nGeneral_Fund_Cash_and_Investments                                                                                                        0.40020185\nGeneral_Fund_Liabilities                                                                                                                 0.51213626\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                                                                1.00000000\nGovernment_Wide_Revenue                                                                                                                  0.86977191\nChange_GF_Unrestricted_Fund_Balances                                                                                                    -0.02268537\nGF_Unrestricted_Fund_Balances                                                                                                            0.41945346\nGF_Expenditures_Transfers_Out                                                                                                            0.70755784\nGF_Unrestricted_FB_PY_PY                                                                                                                 0.42409677\nGF_Unrestricted_FB_PY                                                                                                                    0.45766423\nGF_Unrestricted_FB_CY                                                                                                                    0.41945346\nGF_Rev_PY_PY                                                                                                                             0.70618594\nGF_Rev_PY                                                                                                                                0.70353951\nGF_Rev_CY                                                                                                                                0.68849011\nNet_Pension_Liability_or_Asset                                                                                                           0.72984540\nPension_Related_Debt                                                                                                                     0.31398876\nPension_Assets                                                                                                                           0.82293903\nAccrued_Pension_Liabilities                                                                                                              0.79242509\nActuarially_Determined_Pension_Contributions                                                                                             0.74042984\nProjected_Pension_Contribution                                                                                                           0.75281756\nNet_OPEB_Liability_or_Asset                                                                                                              0.37126679\n                                                                          Government_Wide_Revenue\nPopulation                                                                            0.832527732\nUnemployment_rate                                                                     0.003953211\nGeneral_Fund_Cash_and_Investments                                                     0.660203806\nGeneral_Fund_Liabilities                                                              0.682844220\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations             0.869771907\nGovernment_Wide_Revenue                                                               1.000000000\nChange_GF_Unrestricted_Fund_Balances                                                 -0.039044249\nGF_Unrestricted_Fund_Balances                                                         0.645404929\nGF_Expenditures_Transfers_Out                                                         0.920877340\nGF_Unrestricted_FB_PY_PY                                                              0.645988710\nGF_Unrestricted_FB_PY                                                                 0.696345139\nGF_Unrestricted_FB_CY                                                                 0.645404929\nGF_Rev_PY_PY                                                                          0.917778297\nGF_Rev_PY                                                                             0.920687066\nGF_Rev_CY                                                                             0.916714320\nNet_Pension_Liability_or_Asset                                                        0.919065377\nPension_Related_Debt                                                                  0.340129269\nPension_Assets                                                                        0.947113085\nAccrued_Pension_Liabilities                                                           0.943154540\nActuarially_Determined_Pension_Contributions                                          0.925837620\nProjected_Pension_Contribution                                                        0.934939413\nNet_OPEB_Liability_or_Asset                                                           0.592023702\n                                                                          Change_GF_Unrestricted_Fund_Balances\nPopulation                                                                                         -0.05122791\nUnemployment_rate                                                                                  -0.05626388\nGeneral_Fund_Cash_and_Investments                                                                  -0.04356678\nGeneral_Fund_Liabilities                                                                           -0.02621429\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                          -0.02268537\nGovernment_Wide_Revenue                                                                            -0.03904425\nChange_GF_Unrestricted_Fund_Balances                                                                1.00000000\nGF_Unrestricted_Fund_Balances                                                                      -0.01499481\nGF_Expenditures_Transfers_Out                                                                      -0.04651847\nGF_Unrestricted_FB_PY_PY                                                                           -0.05422690\nGF_Unrestricted_FB_PY                                                                              -0.05574819\nGF_Unrestricted_FB_CY                                                                              -0.01499481\nGF_Rev_PY_PY                                                                                       -0.04722298\nGF_Rev_PY                                                                                          -0.04739149\nGF_Rev_CY                                                                                          -0.04687453\nNet_Pension_Liability_or_Asset                                                                     -0.03771912\nPension_Related_Debt                                                                               -0.01242512\nPension_Assets                                                                                     -0.03674397\nAccrued_Pension_Liabilities                                                                        -0.03705983\nActuarially_Determined_Pension_Contributions                                                       -0.03689249\nProjected_Pension_Contribution                                                                     -0.03781699\nNet_OPEB_Liability_or_Asset                                                                        -0.03009563\n                                                                          GF_Unrestricted_Fund_Balances\nPopulation                                                                                   0.59262806\nUnemployment_rate                                                                           -0.06481346\nGeneral_Fund_Cash_and_Investments                                                            0.81081400\nGeneral_Fund_Liabilities                                                                     0.49972955\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                    0.41945346\nGovernment_Wide_Revenue                                                                      0.64540493\nChange_GF_Unrestricted_Fund_Balances                                                        -0.01499481\nGF_Unrestricted_Fund_Balances                                                                1.00000000\nGF_Expenditures_Transfers_Out                                                                0.70002638\nGF_Unrestricted_FB_PY_PY                                                                     0.88375324\nGF_Unrestricted_FB_PY                                                                        0.91987988\nGF_Unrestricted_FB_CY                                                                        1.00000000\nGF_Rev_PY_PY                                                                                 0.70933864\nGF_Rev_PY                                                                                    0.71031419\nGF_Rev_CY                                                                                    0.71160927\nNet_Pension_Liability_or_Asset                                                               0.58238500\nPension_Related_Debt                                                                         0.21226839\nPension_Assets                                                                               0.59335052\nAccrued_Pension_Liabilities                                                                  0.59117154\nActuarially_Determined_Pension_Contributions                                                 0.60444510\nProjected_Pension_Contribution                                                               0.59581107\nNet_OPEB_Liability_or_Asset                                                                  0.39824983\n                                                                          GF_Expenditures_Transfers_Out\nPopulation                                                                                  0.831924234\nUnemployment_rate                                                                           0.009850446\nGeneral_Fund_Cash_and_Investments                                                           0.797305376\nGeneral_Fund_Liabilities                                                                    0.825192441\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                   0.707557837\nGovernment_Wide_Revenue                                                                     0.920877340\nChange_GF_Unrestricted_Fund_Balances                                                       -0.046518470\nGF_Unrestricted_Fund_Balances                                                               0.700026383\nGF_Expenditures_Transfers_Out                                                               1.000000000\nGF_Unrestricted_FB_PY_PY                                                                    0.739954850\nGF_Unrestricted_FB_PY                                                                       0.776593988\nGF_Unrestricted_FB_CY                                                                       0.700026383\nGF_Rev_PY_PY                                                                                0.993869518\nGF_Rev_PY                                                                                   0.993394697\nGF_Rev_CY                                                                                   0.992036052\nNet_Pension_Liability_or_Asset                                                              0.943431022\nPension_Related_Debt                                                                        0.408407662\nPension_Assets                                                                              0.941921177\nAccrued_Pension_Liabilities                                                                 0.950516198\nActuarially_Determined_Pension_Contributions                                                0.962830312\nProjected_Pension_Contribution                                                              0.948492219\nNet_OPEB_Liability_or_Asset                                                                 0.709776285\n                                                                          GF_Unrestricted_FB_PY_PY\nPopulation                                                                              0.53903592\nUnemployment_rate                                                                      -0.05865349\nGeneral_Fund_Cash_and_Investments                                                       0.84175499\nGeneral_Fund_Liabilities                                                                0.54698719\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations               0.42409677\nGovernment_Wide_Revenue                                                                 0.64598871\nChange_GF_Unrestricted_Fund_Balances                                                   -0.05422690\nGF_Unrestricted_Fund_Balances                                                           0.88375324\nGF_Expenditures_Transfers_Out                                                           0.73995485\nGF_Unrestricted_FB_PY_PY                                                                1.00000000\nGF_Unrestricted_FB_PY                                                                   0.97575550\nGF_Unrestricted_FB_CY                                                                   0.88375324\nGF_Rev_PY_PY                                                                            0.74687428\nGF_Rev_PY                                                                               0.74036509\nGF_Rev_CY                                                                               0.72794307\nNet_Pension_Liability_or_Asset                                                          0.58621253\nPension_Related_Debt                                                                    0.16759023\nPension_Assets                                                                          0.60243181\nAccrued_Pension_Liabilities                                                             0.60181214\nActuarially_Determined_Pension_Contributions                                            0.61746451\nProjected_Pension_Contribution                                                          0.61646760\nNet_OPEB_Liability_or_Asset                                                             0.38179034\n                                                                          GF_Unrestricted_FB_PY\nPopulation                                                                           0.60847563\nUnemployment_rate                                                                   -0.06009481\nGeneral_Fund_Cash_and_Investments                                                    0.88359469\nGeneral_Fund_Liabilities                                                             0.58521821\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations            0.45766423\nGovernment_Wide_Revenue                                                              0.69634514\nChange_GF_Unrestricted_Fund_Balances                                                -0.05574819\nGF_Unrestricted_Fund_Balances                                                        0.91987988\nGF_Expenditures_Transfers_Out                                                        0.77659399\nGF_Unrestricted_FB_PY_PY                                                             0.97575550\nGF_Unrestricted_FB_PY                                                                1.00000000\nGF_Unrestricted_FB_CY                                                                0.91987988\nGF_Rev_PY_PY                                                                         0.78388183\nGF_Rev_PY                                                                            0.78251955\nGF_Rev_CY                                                                            0.77501546\nNet_Pension_Liability_or_Asset                                                       0.63809415\nPension_Related_Debt                                                                 0.22281616\nPension_Assets                                                                       0.64363901\nAccrued_Pension_Liabilities                                                          0.64556000\nActuarially_Determined_Pension_Contributions                                         0.66738140\nProjected_Pension_Contribution                                                       0.65684089\nNet_OPEB_Liability_or_Asset                                                          0.44651167\n                                                                          GF_Unrestricted_FB_CY\nPopulation                                                                           0.59262806\nUnemployment_rate                                                                   -0.06481346\nGeneral_Fund_Cash_and_Investments                                                    0.81081400\nGeneral_Fund_Liabilities                                                             0.49972955\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations            0.41945346\nGovernment_Wide_Revenue                                                              0.64540493\nChange_GF_Unrestricted_Fund_Balances                                                -0.01499481\nGF_Unrestricted_Fund_Balances                                                        1.00000000\nGF_Expenditures_Transfers_Out                                                        0.70002638\nGF_Unrestricted_FB_PY_PY                                                             0.88375324\nGF_Unrestricted_FB_PY                                                                0.91987988\nGF_Unrestricted_FB_CY                                                                1.00000000\nGF_Rev_PY_PY                                                                         0.70933864\nGF_Rev_PY                                                                            0.71031419\nGF_Rev_CY                                                                            0.71160927\nNet_Pension_Liability_or_Asset                                                       0.58238500\nPension_Related_Debt                                                                 0.21226839\nPension_Assets                                                                       0.59335052\nAccrued_Pension_Liabilities                                                          0.59117154\nActuarially_Determined_Pension_Contributions                                         0.60444510\nProjected_Pension_Contribution                                                       0.59581107\nNet_OPEB_Liability_or_Asset                                                          0.39824983\n                                                                          GF_Rev_PY_PY\nPopulation                                                                 0.827330122\nUnemployment_rate                                                          0.004408522\nGeneral_Fund_Cash_and_Investments                                          0.812592300\nGeneral_Fund_Liabilities                                                   0.831508760\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.706185937\nGovernment_Wide_Revenue                                                    0.917778297\nChange_GF_Unrestricted_Fund_Balances                                      -0.047222975\nGF_Unrestricted_Fund_Balances                                              0.709338642\nGF_Expenditures_Transfers_Out                                              0.993869518\nGF_Unrestricted_FB_PY_PY                                                   0.746874284\nGF_Unrestricted_FB_PY                                                      0.783881834\nGF_Unrestricted_FB_CY                                                      0.709338642\nGF_Rev_PY_PY                                                               1.000000000\nGF_Rev_PY                                                                  0.998179565\nGF_Rev_CY                                                                  0.994215761\nNet_Pension_Liability_or_Asset                                             0.944384484\nPension_Related_Debt                                                       0.396606511\nPension_Assets                                                             0.939698514\nAccrued_Pension_Liabilities                                                0.950509065\nActuarially_Determined_Pension_Contributions                               0.964981424\nProjected_Pension_Contribution                                             0.951174292\nNet_OPEB_Liability_or_Asset                                                0.719772928\n                                                                              GF_Rev_PY\nPopulation                                                                 0.8297692013\nUnemployment_rate                                                          0.0004024498\nGeneral_Fund_Cash_and_Investments                                          0.8124663319\nGeneral_Fund_Liabilities                                                   0.8276176842\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.7035395130\nGovernment_Wide_Revenue                                                    0.9206870656\nChange_GF_Unrestricted_Fund_Balances                                      -0.0473914872\nGF_Unrestricted_Fund_Balances                                              0.7103141940\nGF_Expenditures_Transfers_Out                                              0.9933946966\nGF_Unrestricted_FB_PY_PY                                                   0.7403650909\nGF_Unrestricted_FB_PY                                                      0.7825195500\nGF_Unrestricted_FB_CY                                                      0.7103141940\nGF_Rev_PY_PY                                                               0.9981795653\nGF_Rev_PY                                                                  1.0000000000\nGF_Rev_CY                                                                  0.9966048535\nNet_Pension_Liability_or_Asset                                             0.9482628313\nPension_Related_Debt                                                       0.3898758631\nPension_Assets                                                             0.9392259489\nAccrued_Pension_Liabilities                                                0.9517409572\nActuarially_Determined_Pension_Contributions                               0.9674875286\nProjected_Pension_Contribution                                             0.9540846675\nNet_OPEB_Liability_or_Asset                                                0.7202161505\n                                                                             GF_Rev_CY\nPopulation                                                                 0.846959004\nUnemployment_rate                                                          0.003115534\nGeneral_Fund_Cash_and_Investments                                          0.809848335\nGeneral_Fund_Liabilities                                                   0.824642127\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations  0.688490112\nGovernment_Wide_Revenue                                                    0.916714320\nChange_GF_Unrestricted_Fund_Balances                                      -0.046874527\nGF_Unrestricted_Fund_Balances                                              0.711609268\nGF_Expenditures_Transfers_Out                                              0.992036052\nGF_Unrestricted_FB_PY_PY                                                   0.727943067\nGF_Unrestricted_FB_PY                                                      0.775015459\nGF_Unrestricted_FB_CY                                                      0.711609268\nGF_Rev_PY_PY                                                               0.994215761\nGF_Rev_PY                                                                  0.996604853\nGF_Rev_CY                                                                  1.000000000\nNet_Pension_Liability_or_Asset                                             0.950682978\nPension_Related_Debt                                                       0.392488992\nPension_Assets                                                             0.937964723\nAccrued_Pension_Liabilities                                                0.951628735\nActuarially_Determined_Pension_Contributions                               0.967147219\nProjected_Pension_Contribution                                             0.954143576\nNet_OPEB_Liability_or_Asset                                                0.723539196\n                                                                          Net_Pension_Liability_or_Asset\nPopulation                                                                                    0.81784437\nUnemployment_rate                                                                             0.02207047\nGeneral_Fund_Cash_and_Investments                                                             0.70085542\nGeneral_Fund_Liabilities                                                                      0.78867980\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                     0.72984540\nGovernment_Wide_Revenue                                                                       0.91906538\nChange_GF_Unrestricted_Fund_Balances                                                         -0.03771912\nGF_Unrestricted_Fund_Balances                                                                 0.58238500\nGF_Expenditures_Transfers_Out                                                                 0.94343102\nGF_Unrestricted_FB_PY_PY                                                                      0.58621253\nGF_Unrestricted_FB_PY                                                                         0.63809415\nGF_Unrestricted_FB_CY                                                                         0.58238500\nGF_Rev_PY_PY                                                                                  0.94438448\nGF_Rev_PY                                                                                     0.94826283\nGF_Rev_CY                                                                                     0.95068298\nNet_Pension_Liability_or_Asset                                                                1.00000000\nPension_Related_Debt                                                                          0.38653164\nPension_Assets                                                                                0.96516600\nAccrued_Pension_Liabilities                                                                   0.98595204\nActuarially_Determined_Pension_Contributions                                                  0.98763331\nProjected_Pension_Contribution                                                                0.98956209\nNet_OPEB_Liability_or_Asset                                                                   0.72874228\n                                                                          Pension_Related_Debt\nPopulation                                                                          0.32108175\nUnemployment_rate                                                                   0.09698174\nGeneral_Fund_Cash_and_Investments                                                   0.34136911\nGeneral_Fund_Liabilities                                                            0.44621468\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations           0.31398876\nGovernment_Wide_Revenue                                                             0.34012927\nChange_GF_Unrestricted_Fund_Balances                                               -0.01242512\nGF_Unrestricted_Fund_Balances                                                       0.21226839\nGF_Expenditures_Transfers_Out                                                       0.40840766\nGF_Unrestricted_FB_PY_PY                                                            0.16759023\nGF_Unrestricted_FB_PY                                                               0.22281616\nGF_Unrestricted_FB_CY                                                               0.21226839\nGF_Rev_PY_PY                                                                        0.39660651\nGF_Rev_PY                                                                           0.38987586\nGF_Rev_CY                                                                           0.39248899\nNet_Pension_Liability_or_Asset                                                      0.38653164\nPension_Related_Debt                                                                1.00000000\nPension_Assets                                                                      0.46475622\nAccrued_Pension_Liabilities                                                         0.41668538\nActuarially_Determined_Pension_Contributions                                        0.42434185\nProjected_Pension_Contribution                                                      0.30616455\nNet_OPEB_Liability_or_Asset                                                         0.50096801\n                                                                          Pension_Assets\nPopulation                                                                    0.82653615\nUnemployment_rate                                                             0.04362715\nGeneral_Fund_Cash_and_Investments                                             0.67024018\nGeneral_Fund_Liabilities                                                      0.75632879\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations     0.82293903\nGovernment_Wide_Revenue                                                       0.94711309\nChange_GF_Unrestricted_Fund_Balances                                         -0.03674397\nGF_Unrestricted_Fund_Balances                                                 0.59335052\nGF_Expenditures_Transfers_Out                                                 0.94192118\nGF_Unrestricted_FB_PY_PY                                                      0.60243181\nGF_Unrestricted_FB_PY                                                         0.64363901\nGF_Unrestricted_FB_CY                                                         0.59335052\nGF_Rev_PY_PY                                                                  0.93969851\nGF_Rev_PY                                                                     0.93922595\nGF_Rev_CY                                                                     0.93796472\nNet_Pension_Liability_or_Asset                                                0.96516600\nPension_Related_Debt                                                          0.46475622\nPension_Assets                                                                1.00000000\nAccrued_Pension_Liabilities                                                   0.99362133\nActuarially_Determined_Pension_Contributions                                  0.97133418\nProjected_Pension_Contribution                                                0.96610488\nNet_OPEB_Liability_or_Asset                                                   0.65275687\n                                                                          Accrued_Pension_Liabilities\nPopulation                                                                                 0.82658650\nUnemployment_rate                                                                          0.03451973\nGeneral_Fund_Cash_and_Investments                                                          0.69290692\nGeneral_Fund_Liabilities                                                                   0.78147285\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                  0.79242509\nGovernment_Wide_Revenue                                                                    0.94315454\nChange_GF_Unrestricted_Fund_Balances                                                      -0.03705983\nGF_Unrestricted_Fund_Balances                                                              0.59117154\nGF_Expenditures_Transfers_Out                                                              0.95051620\nGF_Unrestricted_FB_PY_PY                                                                   0.60181214\nGF_Unrestricted_FB_PY                                                                      0.64556000\nGF_Unrestricted_FB_CY                                                                      0.59117154\nGF_Rev_PY_PY                                                                               0.95050907\nGF_Rev_PY                                                                                  0.95174096\nGF_Rev_CY                                                                                  0.95162874\nNet_Pension_Liability_or_Asset                                                             0.98595204\nPension_Related_Debt                                                                       0.41668538\nPension_Assets                                                                             0.99362133\nAccrued_Pension_Liabilities                                                                1.00000000\nActuarially_Determined_Pension_Contributions                                               0.98629441\nProjected_Pension_Contribution                                                             0.98727071\nNet_OPEB_Liability_or_Asset                                                                0.68742391\n                                                                          Actuarially_Determined_Pension_Contributions\nPopulation                                                                                                  0.81326159\nUnemployment_rate                                                                                           0.01839492\nGeneral_Fund_Cash_and_Investments                                                                           0.74376035\nGeneral_Fund_Liabilities                                                                                    0.83237643\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                                   0.74042984\nGovernment_Wide_Revenue                                                                                     0.92583762\nChange_GF_Unrestricted_Fund_Balances                                                                       -0.03689249\nGF_Unrestricted_Fund_Balances                                                                               0.60444510\nGF_Expenditures_Transfers_Out                                                                               0.96283031\nGF_Unrestricted_FB_PY_PY                                                                                    0.61746451\nGF_Unrestricted_FB_PY                                                                                       0.66738140\nGF_Unrestricted_FB_CY                                                                                       0.60444510\nGF_Rev_PY_PY                                                                                                0.96498142\nGF_Rev_PY                                                                                                   0.96748753\nGF_Rev_CY                                                                                                   0.96714722\nNet_Pension_Liability_or_Asset                                                                              0.98763331\nPension_Related_Debt                                                                                        0.42434185\nPension_Assets                                                                                              0.97133418\nAccrued_Pension_Liabilities                                                                                 0.98629441\nActuarially_Determined_Pension_Contributions                                                                1.00000000\nProjected_Pension_Contribution                                                                              0.98154011\nNet_OPEB_Liability_or_Asset                                                                                 0.74131614\n                                                                          Projected_Pension_Contribution\nPopulation                                                                                    0.81969997\nUnemployment_rate                                                                             0.01530729\nGeneral_Fund_Cash_and_Investments                                                             0.69843112\nGeneral_Fund_Liabilities                                                                      0.77097538\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                     0.75281756\nGovernment_Wide_Revenue                                                                       0.93493941\nChange_GF_Unrestricted_Fund_Balances                                                         -0.03781699\nGF_Unrestricted_Fund_Balances                                                                 0.59581107\nGF_Expenditures_Transfers_Out                                                                 0.94849222\nGF_Unrestricted_FB_PY_PY                                                                      0.61646760\nGF_Unrestricted_FB_PY                                                                         0.65684089\nGF_Unrestricted_FB_CY                                                                         0.59581107\nGF_Rev_PY_PY                                                                                  0.95117429\nGF_Rev_PY                                                                                     0.95408467\nGF_Rev_CY                                                                                     0.95414358\nNet_Pension_Liability_or_Asset                                                                0.98956209\nPension_Related_Debt                                                                          0.30616455\nPension_Assets                                                                                0.96610488\nAccrued_Pension_Liabilities                                                                   0.98727071\nActuarially_Determined_Pension_Contributions                                                  0.98154011\nProjected_Pension_Contribution                                                                1.00000000\nNet_OPEB_Liability_or_Asset                                                                   0.68834578\n                                                                          Net_OPEB_Liability_or_Asset\nPopulation                                                                                 0.54888106\nUnemployment_rate                                                                          0.07083106\nGeneral_Fund_Cash_and_Investments                                                          0.62947284\nGeneral_Fund_Liabilities                                                                   0.76640255\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations                  0.37126679\nGovernment_Wide_Revenue                                                                    0.59202370\nChange_GF_Unrestricted_Fund_Balances                                                      -0.03009563\nGF_Unrestricted_Fund_Balances                                                              0.39824983\nGF_Expenditures_Transfers_Out                                                              0.70977629\nGF_Unrestricted_FB_PY_PY                                                                   0.38179034\nGF_Unrestricted_FB_PY                                                                      0.44651167\nGF_Unrestricted_FB_CY                                                                      0.39824983\nGF_Rev_PY_PY                                                                               0.71977293\nGF_Rev_PY                                                                                  0.72021615\nGF_Rev_CY                                                                                  0.72353920\nNet_Pension_Liability_or_Asset                                                             0.72874228\nPension_Related_Debt                                                                       0.50096801\nPension_Assets                                                                             0.65275687\nAccrued_Pension_Liabilities                                                                0.68742391\nActuarially_Determined_Pension_Contributions                                               0.74131614\nProjected_Pension_Contribution                                                             0.68834578\nNet_OPEB_Liability_or_Asset                                                                1.00000000\n```\n\n\n:::\n\n```{.r .cell-code}\nheatmap(numeric_corr)\n```\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Summary Statistics for Other Numeric Variables:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics\nsummary(data[45:66])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Population      Unemployment_rate General_Fund_Cash_and_Investments\n Min.   :    285   Min.   :0.00000   Min.   :0.000e+00                \n 1st Qu.:  12513   1st Qu.:0.07300   1st Qu.:5.903e+06                \n Median :  34934   Median :0.09100   Median :1.579e+07                \n Mean   :  74733   Mean   :0.09621   Mean   :4.528e+07                \n 3rd Qu.:  78926   3rd Qu.:0.11500   3rd Qu.:3.674e+07                \n Max.   :3970219   Max.   :0.34100   Max.   :3.492e+09                \n                   NA's   :9         NA's   :1                        \n General_Fund_Liabilities\n Min.   :1.696e+04       \n 1st Qu.:1.287e+06       \n Median :3.063e+06       \n Mean   :1.269e+07       \n 3rd Qu.:7.089e+06       \n Max.   :1.331e+09       \n NA's   :1               \n Primary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations\n Min.   :0.000e+00                                                        \n 1st Qu.:6.536e+06                                                        \n Median :2.280e+07                                                        \n Mean   :2.352e+08                                                        \n 3rd Qu.:7.297e+07                                                        \n Max.   :3.599e+10                                                        \n NA's   :1                                                                \n Government_Wide_Revenue Change_GF_Unrestricted_Fund_Balances\n Min.   :4.330e+05       Min.   : -0.770                     \n 1st Qu.:2.232e+07       1st Qu.: -0.010                     \n Median :5.678e+07       Median :  0.070                     \n Mean   :2.048e+08       Mean   :  1.632                     \n 3rd Qu.:1.300e+08       3rd Qu.:  0.190                     \n Max.   :1.746e+10       Max.   :312.630                     \n NA's   :1               NA's   :1                           \n GF_Unrestricted_Fund_Balances GF_Expenditures_Transfers_Out\n Min.   :  -8141906            Min.   :7.204e+04            \n 1st Qu.:   6068089            1st Qu.:1.312e+07            \n Median :  15923906            Median :3.234e+07            \n Mean   :  39070057            Mean   :9.358e+07            \n 3rd Qu.:  36140557            3rd Qu.:7.498e+07            \n Max.   :2455579000            Max.   :6.179e+09            \n NA's   :1                     NA's   :1                    \n GF_Unrestricted_FB_PY_PY GF_Unrestricted_FB_PY GF_Unrestricted_FB_CY\n Min.   : -17564262       Min.   :  -9959177    Min.   :  -8141906   \n 1st Qu.:   5236011       1st Qu.:   5570489    1st Qu.:   6068089   \n Median :  14149500       Median :  16072906    Median :  15923906   \n Mean   :  34203098       Mean   :  38146357    Mean   :  39070057   \n 3rd Qu.:  31310428       3rd Qu.:  35646382    3rd Qu.:  36140557   \n Max.   :2076452000       Max.   :2390787000    Max.   :2455579000   \n NA's   :2                NA's   :1             NA's   :1            \n  GF_Rev_PY_PY         GF_Rev_PY           GF_Rev_CY        \n Min.   :1.530e+05   Min.   :1.972e+05   Min.   :1.799e+05  \n 1st Qu.:1.205e+07   1st Qu.:1.284e+07   1st Qu.:1.292e+07  \n Median :2.907e+07   Median :3.113e+07   Median :3.046e+07  \n Mean   :8.223e+07   Mean   :9.008e+07   Mean   :8.942e+07  \n 3rd Qu.:6.566e+07   3rd Qu.:7.114e+07   3rd Qu.:7.243e+07  \n Max.   :5.250e+09   Max.   :5.890e+09   Max.   :5.745e+09  \n NA's   :2           NA's   :1           NA's   :1          \n Net_Pension_Liability_or_Asset Pension_Related_Debt Pension_Assets     \n Min.   :-244990000             Min.   :        0    Min.   :5.984e+05  \n 1st Qu.:   8067243             1st Qu.:        0    1st Qu.:2.902e+07  \n Median :  29415004             Median :        0    Median :9.008e+07  \n Mean   : 134881952             Mean   :  7336554    Mean   :4.559e+08  \n 3rd Qu.: 102298823             3rd Qu.:        0    3rd Qu.:2.643e+08  \n Max.   :8541000000             Max.   :484258000    Max.   :4.906e+10  \n NA's   :14                     NA's   :14           NA's   :14         \n Accrued_Pension_Liabilities Actuarially_Determined_Pension_Contributions\n Min.   :6.333e+05           Min.   :3.087e+04                           \n 1st Qu.:3.821e+07           1st Qu.:9.864e+05                           \n Median :1.262e+08           Median :3.367e+06                           \n Mean   :5.930e+08           Mean   :1.679e+07                           \n 3rd Qu.:3.620e+08           3rd Qu.:1.064e+07                           \n Max.   :5.761e+10           Max.   :1.494e+09                           \n NA's   :14                  NA's   :14                                  \n Projected_Pension_Contribution Net_OPEB_Liability_or_Asset\n Min.   :    38509              Min.   :2.917e+04          \n 1st Qu.:  1410980              1st Qu.:2.302e+06          \n Median :  4653424              Median :6.965e+06          \n Mean   : 13601756              Mean   :4.792e+07          \n 3rd Qu.: 14650576              3rd Qu.:2.689e+07          \n Max.   :239393864              Max.   :3.903e+09          \n NA's   :25                     NA's   :100                \n```\n\n\n:::\n:::\n\n\n\n\n\n### Missing Values\n\nConsider using only complete objects or use mean and mode imputation when modeling\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Missing values per variable\nmissing.values <- data.frame(\nMissing_Count = colSums(is.na(data))\n)\nmissing.values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                          Missing_Count\nCity_Name                                                                             0\nOverall_Rank                                                                          0\nGeneral_Fund_Reserves_Rank                                                            0\nDebt_Burden_Rank                                                                      0\nLiquidity_Rank                                                                        0\nRevenue_Trends_Rank                                                                   0\nPension_Obligations_Rank                                                              0\nPension_Funding_Rank                                                                  0\nPension_Costs_Rank                                                                    0\nFuture_Pension_Costs_Rank                                                             0\nOPEB_Obligations_Rank                                                                 0\nOPEB_Funding_Rank                                                                     0\nOverall_Risk                                                                          0\nGeneral_Fund_Reserves_Risk                                                            0\nDebt_Burden_Risk                                                                      0\nLiquidity_Risk                                                                        0\nRevenue_Trends_Risk                                                                   0\nPension_Obligations_Risk                                                              0\nPension_Funding_Risk                                                                  0\nPension_Costs_Risk                                                                    0\nFuture_Pension_Costs_Risk                                                             0\nOPEB_Obligations_Risk                                                                 0\nOPEB_Funding_Risk                                                                     0\nOverall_Points                                                                        0\nGeneral_Fund_Reserves_Points                                                          0\nDebt_Burden_Points                                                                    0\nLiquidity_Points                                                                      0\nRevenue_Trends_Points                                                                 0\nPension_Obligations_Points                                                            0\nPension_Funding_Points                                                                0\nPension_Costs_Points                                                                  0\nFuture_Pension_Costs_Points                                                           0\nOPEB_Obligations_Points                                                               0\nOPEB_Funding_Points                                                                   0\nGeneral_Fund_Reserves_Ratio                                                           1\nDebt_Burden_Ratio                                                                     1\nLiquidity_Ratio                                                                       1\nRevenue_Trends_Ratio                                                                  1\nPension_Obligations_Ratio                                                            14\nPension_Funding_Ratio                                                                14\nPension_Costs_Ratio                                                                  14\nFuture_Pension_Costs_Ratio                                                           25\nOPEB_Obligations_Ratio                                                               77\nOPEB_Funding_Ratio                                                                   77\nPopulation                                                                            0\nUnemployment_rate                                                                     9\nGeneral_Fund_Cash_and_Investments                                                     1\nGeneral_Fund_Liabilities                                                              1\nPrimary_Government_Long_Term_Obligations_Excluding_Retirement_Obligations             1\nGovernment_Wide_Revenue                                                               1\nChange_GF_Unrestricted_Fund_Balances                                                  1\nGF_Unrestricted_Fund_Balances                                                         1\nGF_Expenditures_Transfers_Out                                                         1\nGF_Unrestricted_FB_PY_PY                                                              2\nGF_Unrestricted_FB_PY                                                                 1\nGF_Unrestricted_FB_CY                                                                 1\nGF_Rev_PY_PY                                                                          2\nGF_Rev_PY                                                                             1\nGF_Rev_CY                                                                             1\nNet_Pension_Liability_or_Asset                                                       14\nPension_Related_Debt                                                                 14\nPension_Assets                                                                       14\nAccrued_Pension_Liabilities                                                          14\nActuarially_Determined_Pension_Contributions                                         14\nProjected_Pension_Contribution                                                       25\nNet_OPEB_Liability_or_Asset                                                         100\n```\n\n\n:::\n:::\n\n\n\n\n\n### Boxplots: Points and Risks\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Points by Risk Boxplots\ncat <- 13\nnum <- 24\n\nfor (i in 1:11){\n  # Boxplot\n  cat_col <- names(data)[cat] # Categorical variable\n  num_col <- names(data)[num] # Numeric variable\n\n  y_min <- min(data[[num_col]], na.rm = TRUE)\n  y_max <- max(data[[num_col]], na.rm = TRUE)\n  y_margin <- (y_max - y_min) * 0.1 # Add 10% margin for better centering\n  \n  p <- ggplot(\n    data, \n    aes_string(x = cat_col, y = num_col, fill = cat_col)) + \n    geom_boxplot(alpha = 0.7, outlier.shape = NA) + # Hide outliers for better centering\n    coord_cartesian(ylim = c(y_min - y_margin, y_max + y_margin)) + # Adjust limits dynamically\n    labs(title = paste(\"Boxplot of\", num_col, \"by\", cat_col),\n         x = cat_col,\n         y = num_col,\n         fill = cat_col) +\n    theme_minimal() +\n    theme(axis.text.x = element_text(angle = 45, hjust = 1))\n\n  # Print the plot\n  print(p)\n\n  cat <- cat +1\n  num <- num +1\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\nℹ Please use tidy evaluation idioms with `aes()`.\nℹ See also `vignette(\"ggplot2-in-packages\")` for more information.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-8-11.png){width=672}\n:::\n:::\n\n\n\n\n\nFor each risk category, getting higher points means lower risk in the specific category. However, due to different range of points in different categories overall points are not meaningfully corresponding to overall risk level for the local governments.\n\n### Boxplots: Ratio and Risks\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ratio by Risk\ncat <- 14\nnum <- 35\n\nfor (i in 1:10){\n\n  # Boxplot\n  cat_col <- names(data)[cat] # Categorical variable\n  num_col <- names(data)[num] # Numeric variable\n  y_min <- min(data[[num_col]], na.rm = TRUE)\n  y_max <- max(data[[num_col]], na.rm = TRUE)\n  y_margin <- (y_max - y_min) * 0.1 # Add 10% margin for better centering\n\n  p <- ggplot(data, aes_string(x = cat_col, y = num_col, fill = cat_col)) +\n    geom_boxplot(alpha = 0.7, outlier.shape = NA) + # Hide outliers for better centering\n    coord_cartesian(ylim = c(y_min - y_margin, y_max + y_margin)) + # Adjust limits dynamically\n    labs(title = paste(\"Boxplot of\", num_col, \"by\", cat_col),\n         x = cat_col,\n         y = num_col,\n         fill = cat_col) +\n    theme_minimal() +\n    theme(axis.text.x = element_text(angle = 45, hjust = 1))\n  \n  # Print the plot\n  print(p)\n\n  cat <- cat +1\n  num <- num +1\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 14 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 14 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-6.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 14 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-7.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 25 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-8.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 77 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-9.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 77 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-9-10.png){width=672}\n:::\n:::\n\n\n\n\n\nRatio can potentially be either positively or negatively related to their specific Risks.\n\n### Mean and mode imputation\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n# Impute missing values with column means\ndata_imputed <- data %>%\n  mutate(across(where(is.numeric), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)))\nmissing_counts <- colSums(is.na(data_imputed))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check Missing values per variable after imputation\nmissing.imputed <- data.frame(\n  Missing_Count = colSums(is.na(data_imputed))\n)\nsum(missing.imputed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n\n\n### Histogram of Risk Levels\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of Risk Levels by Variables\ncat <- 13\nfor (i in 1:11) {\n  cat_col <- names(data)[cat] # Categorical variable\n  \n  p <- ggplot(data, aes_string(x = cat_col, fill = cat_col)) +\n    geom_bar() +\n    labs(title = paste(\"Histogram of Risk Levels for\", cat_col),\n         x = cat_col,\n         y = \"Count\",\n         fill = \"Risk Level\") +\n    theme_minimal() +\n    theme(axis.text.x = element_text(angle = 45, hjust = 1))\n  \n  print(p)\n  cat <- cat + 1\n}\n```\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-12-11.png){width=672}\n:::\n:::\n\n\n\n\n\n## 2. Statistic Modeling:\n\n### Ordinal logistic regression:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'MASS' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'MASS'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ordinal)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ordinal' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'ordinal'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    slice\n```\n\n\n:::\n\n```{.r .cell-code}\nordinal_model <- clm(Overall_Risk ~ General_Fund_Reserves_Ratio + Debt_Burden_Ratio + Liquidity_Ratio + Revenue_Trends_Ratio + Pension_Obligations_Ratio + Pension_Funding_Ratio + Pension_Costs_Ratio + Future_Pension_Costs_Ratio + OPEB_Obligations_Ratio + OPEB_Funding_Ratio,\n  data = data_imputed,\n  link = \"logit\"\n)\nsummary(ordinal_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: \nOverall_Risk ~ General_Fund_Reserves_Ratio + Debt_Burden_Ratio + Liquidity_Ratio + Revenue_Trends_Ratio + Pension_Obligations_Ratio + Pension_Funding_Ratio + Pension_Costs_Ratio + Future_Pension_Costs_Ratio + OPEB_Obligations_Ratio + OPEB_Funding_Ratio\ndata:    data_imputed\n\n link  threshold nobs logLik  AIC    niter max.grad cond.H \n logit flexible  423  -267.17 558.34 7(0)  1.50e-09 4.7e+05\n\nCoefficients:\n                            Estimate Std. Error z value Pr(>|z|)    \nGeneral_Fund_Reserves_Ratio -0.24111    0.08069  -2.988  0.00281 ** \nDebt_Burden_Ratio            0.58626    0.21870   2.681  0.00735 ** \nLiquidity_Ratio             -0.06083    0.01540  -3.950  7.8e-05 ***\nRevenue_Trends_Ratio        -2.20938    1.71059  -1.292  0.19650    \nPension_Obligations_Ratio    1.16436    0.56056   2.077  0.03779 *  \nPension_Funding_Ratio        1.74199    1.57109   1.109  0.26753    \nPension_Costs_Ratio         -5.52329    6.08241  -0.908  0.36384    \nFuture_Pension_Costs_Ratio  14.62631    5.26400   2.779  0.00546 ** \nOPEB_Obligations_Ratio      -0.02841    0.70131  -0.041  0.96769    \nOPEB_Funding_Ratio          -1.03841    0.36949  -2.810  0.00495 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n              Estimate Std. Error z value\nLOW|MODERATE    -2.319      1.425  -1.627\nMODERATE|HIGH    2.458      1.380   1.781\n```\n\n\n:::\n:::\n\n\n\n\n\n## 3. Predictive Modeling:\n\n### Random Forests:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(randomForest)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'randomForest' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrandomForest 4.7-1.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nType rfNews() to see new features/changes/bug fixes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'randomForest'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    combine\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:ggplot2':\n\n    margin\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(gbm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'gbm' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoaded gbm 2.2.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis version of gbm is no longer under development. Consider transitioning to gbm3, https://github.com/gbm-developers/gbm3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'caret' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'caret'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    lift\n```\n\n\n:::\n\n```{.r .cell-code}\nselected_vars <- c(\"Overall_Risk\", \"General_Fund_Reserves_Ratio\", \"Debt_Burden_Ratio\", \n                   \"Liquidity_Ratio\", \"Revenue_Trends_Ratio\", \"Pension_Obligations_Ratio\", \n                   \"Pension_Funding_Ratio\", \"Pension_Costs_Ratio\", \n                   \"Future_Pension_Costs_Ratio\", \"OPEB_Obligations_Ratio\", \"OPEB_Funding_Ratio\")\n\ndata_selected <- data_imputed[, selected_vars]\n\n# Split data into training (70%) and testing (30%) sets\nset.seed(101)\ntrain_index <- createDataPartition(data_selected$Overall_Risk, p = 0.7, list = FALSE)\ntrain_data <- data_selected[train_index, ]\ntest_data <- data_selected[-train_index, ]\n\nset.seed(101)\nrf_model <- randomForest(Overall_Risk ~ ., data = train_data, \n                         mtry = ncol(train_data) - 1, importance = TRUE)\n\nprint(rf_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\n randomForest(formula = Overall_Risk ~ ., data = train_data, mtry = ncol(train_data) -      1, importance = TRUE) \n               Type of random forest: classification\n                     Number of trees: 500\nNo. of variables tried at each split: 10\n\n        OOB estimate of  error rate: 12.42%\nConfusion matrix:\n         LOW MODERATE HIGH class.error\nLOW        3        1    5   0.6666667\nMODERATE   0      135   16   0.1059603\nHIGH       3       12  123   0.1086957\n```\n\n\n:::\n:::\n\n\n\n\n\nHere we fit a Random Forest Model using 10 splits (all predictors). Looking at the results, we see an OOB error rate of 12.42% which means that the model misclassifies about 12.42% total observations. Furthermore, we can see that the Random Forest model tends to have a harder time predicted for the class \"LOW.\" While the OOB error rate is relatively low, the class.error for LOW is extremely high.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Variable Importance Plot\nimportance(rf_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                   LOW  MODERATE      HIGH MeanDecreaseAccuracy\nGeneral_Fund_Reserves_Ratio 17.5817197 60.107365 78.766294            93.194022\nDebt_Burden_Ratio            1.0786688  8.128296  9.917937            12.218631\nLiquidity_Ratio             11.6225670  1.747423 14.461770            16.173105\nRevenue_Trends_Ratio         1.2192035 -1.619935 -1.911778            -2.209593\nPension_Obligations_Ratio   11.2341174 23.078055 24.191498            33.094629\nPension_Funding_Ratio        4.0108439  6.602884  6.661010             9.119146\nPension_Costs_Ratio          1.6470805  9.396006  3.779072            10.103250\nFuture_Pension_Costs_Ratio   7.5146768 10.120949  7.740986            13.408256\nOPEB_Obligations_Ratio       1.8499933 11.447187  1.947810             9.984454\nOPEB_Funding_Ratio           0.3245529  8.479432 13.106371            14.777234\n                            MeanDecreaseGini\nGeneral_Fund_Reserves_Ratio        96.359249\nDebt_Burden_Ratio                   7.400525\nLiquidity_Ratio                     9.142545\nRevenue_Trends_Ratio                2.940298\nPension_Obligations_Ratio          17.871268\nPension_Funding_Ratio               4.320126\nPension_Costs_Ratio                 2.571313\nFuture_Pension_Costs_Ratio          5.940656\nOPEB_Obligations_Ratio              5.000233\nOPEB_Funding_Ratio                  5.173426\n```\n\n\n:::\n\n```{.r .cell-code}\nvarImpPlot(rf_model)\n```\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n\nVariable importance for the Random Forest model was determined through: 1) Mean Decrease in Accuracy, and 2) Mean Decrease in Gini Impurity.\n\nThe first evaluates the model's accuracy by permuting each variable while the second shows how impurity in tree splits are reduced based on a variable's significance. In both these charts, general fund reserves has the greatest value. In other words, the general fund reserve is a significant contributor to predicting the overall risk.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict on test data\nrf_predictions <- predict(rf_model, newdata = test_data)\n\n# Confusion Matrix and Accuracy\nrf_conf_matrix <- confusionMatrix(rf_predictions, test_data$Overall_Risk)\nprint(rf_conf_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction LOW MODERATE HIGH\n  LOW        2        0    0\n  MODERATE   0       59    2\n  HIGH       1        5   56\n\nOverall Statistics\n                                         \n               Accuracy : 0.936          \n                 95% CI : (0.8778, 0.972)\n    No Information Rate : 0.512          \n    P-Value [Acc > NIR] : < 2.2e-16      \n                                         \n                  Kappa : 0.8768         \n                                         \n Mcnemar's Test P-Value : NA             \n\nStatistics by Class:\n\n                     Class: LOW Class: MODERATE Class: HIGH\nSensitivity              0.6667          0.9219      0.9655\nSpecificity              1.0000          0.9672      0.9104\nPos Pred Value           1.0000          0.9672      0.9032\nNeg Pred Value           0.9919          0.9219      0.9683\nPrevalence               0.0240          0.5120      0.4640\nDetection Rate           0.0160          0.4720      0.4480\nDetection Prevalence     0.0160          0.4880      0.4960\nBalanced Accuracy        0.8333          0.9445      0.9380\n```\n\n\n:::\n:::\n\n\n\n\n\nUsing our Random Forest model based on our training data, the prediction accuracy relatively high at 93.6%.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### XGBOOST MODEL ###\n# Prepare data for XGBoost\nselected_vars_xg <- c(\"Overall_Risk\", \"General_Fund_Reserves_Ratio\", \"Debt_Burden_Ratio\", \n                   \"Liquidity_Ratio\", \"Revenue_Trends_Ratio\", \"Pension_Obligations_Ratio\", \n                   \"Pension_Funding_Ratio\", \"Pension_Costs_Ratio\", \n                   \"Future_Pension_Costs_Ratio\", \"OPEB_Obligations_Ratio\", \"OPEB_Funding_Ratio\")\n\ndata_selected_xg <- data_imputed[, selected_vars_xg]\n\nset.seed(101)\ntrain_index_xg <- createDataPartition(data_selected_xg$Overall_Risk, p = 0.7, list = FALSE)\ntrain_data_xg <- data_selected[train_index_xg, ]\ntest_data_xg <- data_selected[-train_index_xg, ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressWarnings({\n  library(tidyverse)\n  library(caret)\n  library(xgboost)\n})\n\ntrain_control <- trainControl(method = \"cv\", number = 10)  # 10-fold CV\n\n# Train XGBoost model\nset.seed(101)\nxgb_model <- train(\n  Overall_Risk ~ ., \n  data = train_data_xg, \n  method = \"xgbTree\", \n  trControl = train_control,\n  verbose = FALSE,\n  verbosity = 0\n)\n\n# Print model summary\nprint(xgb_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neXtreme Gradient Boosting \n\n298 samples\n 10 predictor\n  3 classes: 'LOW', 'MODERATE', 'HIGH' \n\nNo pre-processing\nResampling: Cross-Validated (10 fold) \nSummary of sample sizes: 269, 269, 268, 268, 269, 268, ... \nResampling results across tuning parameters:\n\n  eta  max_depth  colsample_bytree  subsample  nrounds  Accuracy   Kappa    \n  0.3  1          0.6               0.50        50      0.8894105  0.7865674\n  0.3  1          0.6               0.50       100      0.9063070  0.8200302\n  0.3  1          0.6               0.50       150      0.9028587  0.8130274\n  0.3  1          0.6               0.75        50      0.8960771  0.7985020\n  0.3  1          0.6               0.75       100      0.8997479  0.8065433\n  0.3  1          0.6               0.75       150      0.9028587  0.8142615\n  0.3  1          0.6               1.00        50      0.8827364  0.7726474\n  0.3  1          0.6               1.00       100      0.8894030  0.7867612\n  0.3  1          0.6               1.00       150      0.8896329  0.7884062\n  0.3  1          0.8               0.50        50      0.8859622  0.7794157\n  0.3  1          0.8               0.50       100      0.9026437  0.8119677\n  0.3  1          0.8               0.50       150      0.9095402  0.8259553\n  0.3  1          0.8               0.75        50      0.8859622  0.7796084\n  0.3  1          0.8               0.75       100      0.8996403  0.8067785\n  0.3  1          0.8               0.75       150      0.9096403  0.8266797\n  0.3  1          0.8               1.00        50      0.8727364  0.7527284\n  0.3  1          0.8               1.00       100      0.8860697  0.7802539\n  0.3  1          0.8               1.00       150      0.8795180  0.7695893\n  0.3  2          0.6               0.50        50      0.9158621  0.8368408\n  0.3  2          0.6               0.50       100      0.9126363  0.8312833\n  0.3  2          0.6               0.50       150      0.9159696  0.8377627\n  0.3  2          0.6               0.75        50      0.9126363  0.8312135\n  0.3  2          0.6               0.75       100      0.9094179  0.8256865\n  0.3  2          0.6               0.75       150      0.9129737  0.8334898\n  0.3  2          0.6               1.00        50      0.8994179  0.8062013\n  0.3  2          0.6               1.00       100      0.9059770  0.8184353\n  0.3  2          0.6               1.00       150      0.9125287  0.8312164\n  0.3  2          0.8               0.50        50      0.9093103  0.8247460\n  0.3  2          0.8               0.50       100      0.9260920  0.8571951\n  0.3  2          0.8               0.50       150      0.9227586  0.8510944\n  0.3  2          0.8               0.75        50      0.9058547  0.8180022\n  0.3  2          0.8               0.75       100      0.9195328  0.8448847\n  0.3  2          0.8               0.75       150      0.9094179  0.8255420\n  0.3  2          0.8               1.00        50      0.8959696  0.7994848\n  0.3  2          0.8               1.00       100      0.9094253  0.8254197\n  0.3  2          0.8               1.00       150      0.9125287  0.8314302\n  0.3  3          0.6               0.50        50      0.9263144  0.8580679\n  0.3  3          0.6               0.50       100      0.9163070  0.8385977\n  0.3  3          0.6               0.50       150      0.9128587  0.8325332\n  0.3  3          0.6               0.75        50      0.9028587  0.8132026\n  0.3  3          0.6               0.75       100      0.9027438  0.8132045\n  0.3  3          0.6               0.75       150      0.9094105  0.8261078\n  0.3  3          0.6               1.00        50      0.9191954  0.8440368\n  0.3  3          0.6               1.00       100      0.9259770  0.8577046\n  0.3  3          0.6               1.00       150      0.9226437  0.8515850\n  0.3  3          0.8               0.50        50      0.9194179  0.8453759\n  0.3  3          0.8               0.50       100      0.9263144  0.8590132\n  0.3  3          0.8               0.50       150      0.9296552  0.8649878\n  0.3  3          0.8               0.75        50      0.9093029  0.8258588\n  0.3  3          0.8               0.75       100      0.9094179  0.8262194\n  0.3  3          0.8               0.75       150      0.9128661  0.8331406\n  0.3  3          0.8               1.00        50      0.8889655  0.7855703\n  0.3  3          0.8               1.00       100      0.9093103  0.8259123\n  0.3  3          0.8               1.00       150      0.9059770  0.8198518\n  0.4  1          0.6               0.50        50      0.8994179  0.8051958\n  0.4  1          0.6               0.50       100      0.9093029  0.8256242\n  0.4  1          0.6               0.50       150      0.8927438  0.7944480\n  0.4  1          0.6               0.75        50      0.8960771  0.7981854\n  0.4  1          0.6               0.75       100      0.9098628  0.8269722\n  0.4  1          0.6               0.75       150      0.9097553  0.8270636\n  0.4  1          0.6               1.00        50      0.8828513  0.7731589\n  0.4  1          0.6               1.00       100      0.8996329  0.8061801\n  0.4  1          0.6               1.00       150      0.8962996  0.8010116\n  0.4  1          0.8               0.50        50      0.9061921  0.8194954\n  0.4  1          0.8               0.50       100      0.9228661  0.8513439\n  0.4  1          0.8               0.50       150      0.9227512  0.8505528\n  0.4  1          0.8               0.75        50      0.8996403  0.8061267\n  0.4  1          0.8               0.75       100      0.9129737  0.8325301\n  0.4  1          0.8               0.75       150      0.9097553  0.8261552\n  0.4  1          0.8               1.00        50      0.8892955  0.7853666\n  0.4  1          0.8               1.00       100      0.8962996  0.7997773\n  0.4  1          0.8               1.00       150      0.8896329  0.7893759\n  0.4  2          0.6               0.50        50      0.9061995  0.8188723\n  0.4  2          0.6               0.50       100      0.9197627  0.8457372\n  0.4  2          0.6               0.50       150      0.9230960  0.8521505\n  0.4  2          0.6               0.75        50      0.8927438  0.7929293\n  0.4  2          0.6               0.75       100      0.9059696  0.8186881\n  0.4  2          0.6               0.75       150      0.9195328  0.8454352\n  0.4  2          0.6               1.00        50      0.9026437  0.8130443\n  0.4  2          0.6               1.00       100      0.9260920  0.8578545\n  0.4  2          0.6               1.00       150      0.9058547  0.8201034\n  0.4  2          0.8               0.50        50      0.9130886  0.8326291\n  0.4  2          0.8               0.50       100      0.9165369  0.8400269\n  0.4  2          0.8               0.50       150      0.9130886  0.8331662\n  0.4  2          0.8               0.75        50      0.9126363  0.8311069\n  0.4  2          0.8               0.75       100      0.9093029  0.8255653\n  0.4  2          0.8               0.75       150      0.9126363  0.8319615\n  0.4  2          0.8               1.00        50      0.9060845  0.8194710\n  0.4  2          0.8               1.00       100      0.9128661  0.8329472\n  0.4  2          0.8               1.00       150      0.9094179  0.8265390\n  0.4  3          0.6               0.50        50      0.9128587  0.8325461\n  0.4  3          0.6               0.50       100      0.9026288  0.8124190\n  0.4  3          0.6               0.50       150      0.9060771  0.8191629\n  0.4  3          0.6               0.75        50      0.9196403  0.8456536\n  0.4  3          0.6               0.75       100      0.9161921  0.8389578\n  0.4  3          0.6               0.75       150      0.9127438  0.8320694\n  0.4  3          0.6               1.00        50      0.9090805  0.8247751\n  0.4  3          0.6               1.00       100      0.9159770  0.8380401\n  0.4  3          0.6               1.00       150      0.9127512  0.8320900\n  0.4  3          0.8               0.50        50      0.9126363  0.8313815\n  0.4  3          0.8               0.50       100      0.9160845  0.8380326\n  0.4  3          0.8               0.50       150      0.9194179  0.8444014\n  0.4  3          0.8               0.75        50      0.9160845  0.8384068\n  0.4  3          0.8               0.75       100      0.9195328  0.8451096\n  0.4  3          0.8               0.75       150      0.9195328  0.8453370\n  0.4  3          0.8               1.00        50      0.8956322  0.7996097\n  0.4  3          0.8               1.00       100      0.9025287  0.8127853\n  0.4  3          0.8               1.00       150      0.8991954  0.8067249\n\nTuning parameter 'gamma' was held constant at a value of 0\nTuning\n parameter 'min_child_weight' was held constant at a value of 1\nAccuracy was used to select the optimal model using the largest value.\nThe final values used for the model were nrounds = 150, max_depth = 3, eta\n = 0.3, gamma = 0, colsample_bytree = 0.8, min_child_weight = 1 and subsample\n = 0.5.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Predict on test data\nxgb_predictions <- predict(xgb_model, newdata = test_data_xg)\n\n# Confusion Matrix and Accuracy\nxgb_conf_matrix <- confusionMatrix(xgb_predictions, test_data_xg$Overall_Risk)\nprint(xgb_conf_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction LOW MODERATE HIGH\n  LOW        2        0    0\n  MODERATE   0       59    4\n  HIGH       1        5   54\n\nOverall Statistics\n                                         \n               Accuracy : 0.92           \n                 95% CI : (0.8578, 0.961)\n    No Information Rate : 0.512          \n    P-Value [Acc > NIR] : < 2.2e-16      \n                                         \n                  Kappa : 0.8458         \n                                         \n Mcnemar's Test P-Value : NA             \n\nStatistics by Class:\n\n                     Class: LOW Class: MODERATE Class: HIGH\nSensitivity              0.6667          0.9219      0.9310\nSpecificity              1.0000          0.9344      0.9104\nPos Pred Value           1.0000          0.9365      0.9000\nNeg Pred Value           0.9919          0.9194      0.9385\nPrevalence               0.0240          0.5120      0.4640\nDetection Rate           0.0160          0.4720      0.4320\nDetection Prevalence     0.0160          0.5040      0.4800\nBalanced Accuracy        0.8333          0.9282      0.9207\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_importance <- varImp(xgb_model, scale = FALSE)\n\n# Plot importance\nplot(feature_importance, main = \"Feature Importance in XGBoost Model\")\n```\n\n::: {.cell-output-display}\n![](stats140xp_project_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n\nWe created an eXtreme Gradient Boosting (XGBoost) predictive model. The XGBoost model was trained using 10-fold cross validation and applied to the training dataset. The model was tuned using hyperparameters nrounds = 150, max_depth = 3, eta = 0.3, gamma = 0, colsample_bytree = 0.8, min_child_weight = 1 and subsample = 0.5.\n\nSimilar to the Random Forest model, the XGBoost model also performed relatively well achieving a prediction accuracy of 92%. Furthermore, looking at the statistics by class, we see the \"LOW\" class has the lowest prediction accuracy with only 2 out of 3 cases being correctly classified. On the other hand, levels like \"MODERATE\" and \"HIGH\" had a much higher classification rate. These results look very similar to our Random Forest model.\n\nFurthermore, while looking at the feature importance plot, we see similar results of general fund reserves being a key contributor for risk classification.\n\nHowever, unlike the Random Forest model, the XGBoost model is computationally expensive and even achieved a slightly lower accuracy rate. Due to its complexity and slower learning method of fitting each decision tree sequentially, there is a possibility that our data has been overfit.\n",
    "supporting": [
      "stats140xp_project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}